import {
	resolveDispatchPort,
	type IDispatchPort,
} from '@mcp-vertex/agent-orchestrator/public';
import { definePlugin, toolError } from '@mcp-vertex/core/public';
import z from 'zod';

import {
	buildOrchestratePlanRegistration,
	buildOrchestrateRunRegistration,
} from './lib/tools/orchestrate.tool';

const OptionsSchema = z
	.object({
		policy: z
			.object({
				defaultMode: z.enum(['single', 'linear', 'swarm', 'auto']),
			})
			.partial()
			.optional(),
		/** Host-provided real dispatch port factory. */
		dispatchPortFactory: z.unknown().optional(),
		/** Tests/fixtures only. Never enables production execution silently. */
		allowFakeDispatchPort: z.boolean().optional(),
	})
	.strict();

export default definePlugin({
	name: 'audit-orchestrator',
	version: '0.1.0',
	describe:
		'Project-agnostic orchestration of implementation work generated by audit plan proposals.',
	dependsOn: ['agent-orchestrator'],
	optionsSchema: OptionsSchema,
	register(ctx) {
		const parsed = OptionsSchema.safeParse(ctx.options ?? {});
		if (!parsed.success) {
			return {
				tools: [],
				knowledge: [],
				errors: [
					toolError(
						'invalid-options',
						`Fix plugins.audit-orchestrator.options: ${parsed.error.message}`,
					),
				],
			};
		}

		const options = parsed.data;
		const dispatchPort = (): IDispatchPort =>
			resolveDispatchPort({
				...(options.dispatchPortFactory !== undefined
					? { portFactory: options.dispatchPortFactory }
					: {}),
				...(options.allowFakeDispatchPort !== undefined
					? { allowFakeDispatchPort: options.allowFakeDispatchPort }
					: {}),
			});

		return {
			tools: [
				buildOrchestratePlanRegistration({
					namespacePrefix: ctx.namespacePrefix,
					workspace: ctx.workspace,
				}),
				buildOrchestrateRunRegistration({
					namespacePrefix: ctx.namespacePrefix,
					workspace: ctx.workspace,
					dispatchPort,
				}),
			],
			knowledge: [
				{
					id: 'audit-orchestrator-overview',
					title: 'Audit orchestrator — plan execution',
					body: [
						'# Audit orchestrator',
						'',
						'Reads a `type: plan` audit proposal, derives ordered implementation tasks, and delegates them through the host subagent port.',
						'',
						'`audit_orchestrate_plan` is read-only and previews the derived tasks.',
						'`audit_orchestrate_run` defaults to `dryRun: true`; real execution requires `dryRun: false` and an explicit host `dispatchPortFactory`.',
						'The plugin does not select a vendor or model. The host dispatch port owns provider selection, credentials, worktrees, and agent lifecycle.',
					].join('\n'),
				},
			],
		};
	},
});
