// i18n catalogue for `delendai_external-mcps_call`.
//
// Per-tool i18n entry (f00068 S4). The 12-lang invariant is enforced by
// `check-i18n.ts` once the entry opts in via `apps/web/src/i18n/tools/index.ts`.

import type { IToolI18n } from '#I18N/tools/_shape';

export const externalMcpsCallI18n: IToolI18n = {
	description: {
		en: 'Invoke a tool on a declared external server through the ext.<server>.<tool> proxy. The subprocess boots lazily on the first call and is reused afterwards; the first call pays the cold-boot cost. Calls are contained to the workspace and results are redacted before anything durable is written. When requireHumanAckWhenLlmDecides is on, a server without an accepted ack is blocked with a structured hint to run the ack flow first.',
		es: 'Invoca una herramienta en un servidor externo declarado a través del proxy ext.<server>.<tool>. El subproceso arranca de forma perezosa en la primera llamada y luego se reutiliza; la primera llamada paga el coste de arranque en frío. Las llamadas están contenidas al espacio de trabajo y los resultados se redactan antes de escribir nada duradero. Cuando requireHumanAckWhenLlmDecides está activo, un servidor sin aprobación aceptada se bloquea con una pista estructurada para ejecutar antes el flujo de aprobación.',
		fr: 'Invoque un outil sur un serveur externe déclaré via le proxy ext.<server>.<tool>. Le sous-processus démarre paresseusement au premier appel puis est réutilisé ; le premier appel paie le coût du démarrage à froid. Les appels sont confinés à l’espace de travail et les résultats sont expurgés avant toute écriture durable. Quand requireHumanAckWhenLlmDecides est actif, un serveur sans validation acceptée est bloqué avec un indice structuré invitant à lancer d’abord le flux d’aval.',
		de: 'Ruft ein Werkzeug auf einem deklarierten externen Server über den ext.<server>.<tool>-Proxy auf. Der Subprozess startet beim ersten Aufruf verzögert und wird danach wiederverwendet; der erste Aufruf zahlt die Kaltstartkosten. Aufrufe sind auf den Workspace eingegrenzt und Ergebnisse werden redigiert, bevor etwas Dauerhaftes geschrieben wird. Ist requireHumanAckWhenLlmDecides aktiv, wird ein Server ohne akzeptierte Bestätigung mit einem strukturierten Hinweis blockiert, zuerst den Ack-Fluss auszuführen.',
		it: 'Invoca uno strumento su un server esterno dichiarato tramite il proxy ext.<server>.<tool>. Il sottoprocesso si avvia in modo lazy alla prima chiamata e poi viene riutilizzato; la prima chiamata paga il costo di avvio a freddo. Le chiamate sono contenute nel workspace e i risultati vengono oscurati prima di scrivere qualcosa di duraturo. Quando requireHumanAckWhenLlmDecides è attivo, un server senza approvazione accettata è bloccato con un suggerimento strutturato per eseguire prima il flusso di ack.',
		pt: 'Invoca uma ferramenta num servidor externo declarado através do proxy ext.<server>.<tool>. O subprocesso arranca de forma preguiçosa na primeira chamada e é reutilizado depois; a primeira chamada paga o custo de arranque a frio. As chamadas estão contidas no espaço de trabalho e os resultados são redigidos antes de escrever algo durável. Quando requireHumanAckWhenLlmDecides está ativo, um servidor sem aprovação aceite é bloqueado com uma dica estruturada para executar primeiro o fluxo de aprovação.',
		ja: 'ext.<server>.<tool> プロキシ経由で、宣言済みの外部サーバー上のツールを呼び出します。サブプロセスは最初の呼び出しで遅延起動し、以降は再利用されます。最初の呼び出しがコールドブートのコストを払います。呼び出しはワークスペースに封じ込められ、結果は永続的な書き込みの前に秘匿化されます。requireHumanAckWhenLlmDecides が有効な場合、承認済み ack のないサーバーはブロックされ、先に ack フローを実行するよう構造化されたヒントが返ります。',
		zh: '通过 ext.<server>.<tool> 代理调用已声明外部服务器上的某个工具。子进程在首次调用时惰性启动,之后复用;首次调用付出冷启动成本。调用被限制在工作区内,结果在写入任何持久内容之前会被脱敏。当 requireHumanAckWhenLlmDecides 开启时,没有已接受确认的服务器会被阻止,并返回一条结构化提示,要求先运行确认流程。',
		hi: 'ext.<server>.<tool> प्रॉक्सी के माध्यम से किसी घोषित बाहरी सर्वर पर एक उपकरण को आमंत्रित करें। उप-प्रक्रिया पहली कॉल पर आलसी रूप से बूट होती है और उसके बाद पुन: उपयोग होती है; पहली कॉल कोल्ड-बूट की लागत चुकाती है। कॉल वर्कस्पेस तक सीमित होती हैं और किसी भी स्थायी लेखन से पहले परिणाम redacted किए जाते हैं। जब requireHumanAckWhenLlmDecides चालू हो, तो स्वीकृत ack के बिना सर्वर अवरुद्ध रहता है और पहले ack प्रवाह चलाने का एक संरचित संकेत मिलता है।',
		ar: 'يستدعي أداةً على خادم خارجي معلَن عبر وكيل ext.<server>.<tool>. تُقلَع العملية الفرعية بكسل عند أول استدعاء ثم يُعاد استخدامها؛ ويتحمّل أول استدعاء تكلفة الإقلاع البارد. الاستدعاءات محصورة داخل مساحة العمل، وتُنقَّح النتائج قبل كتابة أي شيء دائم. وعند تفعيل requireHumanAckWhenLlmDecides، يُحظر أي خادم بلا موافقة مقبولة مع تلميح منظّم لتشغيل مسار الموافقة أولًا.',
		th: 'เรียกใช้เครื่องมือบนเซิร์ฟเวอร์ภายนอกที่ประกาศไว้ผ่านพร็อกซี ext.<server>.<tool> กระบวนการย่อยจะบูตแบบ lazy ในการเรียกครั้งแรกและถูกใช้ซ้ำหลังจากนั้น; การเรียกครั้งแรกจ่ายต้นทุนการบูตเย็น การเรียกถูกจำกัดอยู่ในพื้นที่ทำงานและผลลัพธ์ถูกปิดบังก่อนเขียนสิ่งใดที่คงทน เมื่อเปิด requireHumanAckWhenLlmDecides เซิร์ฟเวอร์ที่ไม่มี ack ที่ยอมรับแล้วจะถูกบล็อกพร้อมคำใบ้แบบมีโครงสร้างให้รันกระบวนการ ack ก่อน',
		vi: 'Gọi một công cụ trên máy chủ ngoài đã khai báo thông qua proxy ext.<server>.<tool>. Tiến trình con khởi động lười ở lần gọi đầu và được tái sử dụng sau đó; lần gọi đầu trả chi phí khởi động nguội. Các lệnh gọi được giới hạn trong không gian làm việc và kết quả được ẩn thông tin nhạy cảm trước khi ghi bất cứ thứ gì bền vững. Khi requireHumanAckWhenLlmDecides bật, một máy chủ chưa có ack được chấp nhận sẽ bị chặn kèm gợi ý có cấu trúc yêu cầu chạy luồng ack trước.',
	},
};
