// i18n catalogue for `delendai_external-mcps_suggest`.
//
// Per-tool i18n entry (f00068 S4). The 12-lang invariant is enforced by
// `check-i18n.ts` once the entry opts in via `apps/web/src/i18n/tools/index.ts`.

import type { IToolI18n } from '#I18N/tools/_shape';

export const externalMcpsSuggestI18n: IToolI18n = {
	description: {
		en: 'Describe a capability gap in free text (need) and get up to 3 catalog candidates, each with a one-line rationale, plus an RFC 6902 JSON Patch that ADDS them to the external-servers config (pinned versions, env var NAMES only; already-declared ids skipped). This tool NEVER writes: dry-run the patch with validate_config, apply it only on user confirm, and remember activation is still gated by the human ack flow. Pure and offline.',
		es: 'Describe una carencia de capacidad en texto libre (need) y obtén hasta 3 candidatos del catálogo, cada uno con una justificación de una línea, más un parche JSON RFC 6902 que los AÑADE a la configuración de servidores externos (versiones fijadas, solo NOMBRES de variables de entorno; se omiten los ids ya declarados). Esta herramienta NUNCA escribe: valida el parche en seco con validate_config, aplícalo solo con confirmación del usuario y recuerda que la activación aún depende del flujo de aprobación humana. Puro y sin conexión.',
		fr: 'Décrivez un manque de capacité en texte libre (need) et obtenez jusqu’à 3 candidats du catalogue, chacun avec une justification d’une ligne, plus un patch JSON RFC 6902 qui les AJOUTE à la configuration des serveurs externes (versions épinglées, NOMS de variables d’environnement uniquement ; les ids déjà déclarés sont ignorés). Cet outil n’écrit JAMAIS : validez le patch à blanc avec validate_config, appliquez-le seulement après confirmation de l’utilisateur, et rappelez-vous que l’activation reste soumise au flux d’aval humain. Pur et hors ligne.',
		de: 'Beschreibe eine Fähigkeitslücke in Freitext (need) und erhalte bis zu 3 Katalog-Kandidaten, jeweils mit einer einzeiligen Begründung, plus einen RFC-6902-JSON-Patch, der sie zur Konfiguration externer Server HINZUFÜGT (gepinnte Versionen, nur Umgebungsvariablen-NAMEN; bereits deklarierte IDs werden übersprungen). Dieses Werkzeug schreibt NIE: prüfe den Patch per Trockenlauf mit validate_config, wende ihn nur nach Nutzerbestätigung an und bedenke, dass die Aktivierung weiterhin dem menschlichen Ack-Fluss unterliegt. Rein und offline.',
		it: 'Descrivi una lacuna di capacità in testo libero (need) e ottieni fino a 3 candidati dal catalogo, ciascuno con una motivazione di una riga, più una patch JSON RFC 6902 che li AGGIUNGE alla configurazione dei server esterni (versioni fissate, solo NOMI di variabili d’ambiente; gli id già dichiarati vengono saltati). Questo strumento non scrive MAI: valida la patch a secco con validate_config, applicala solo dopo conferma dell’utente e ricorda che l’attivazione resta soggetta al flusso di ack umano. Puro e offline.',
		pt: 'Descreva uma lacuna de capacidade em texto livre (need) e obtenha até 3 candidatos do catálogo, cada um com uma justificação de uma linha, mais um patch JSON RFC 6902 que os ADICIONA à configuração de servidores externos (versões fixadas, apenas NOMES de variáveis de ambiente; ids já declarados são ignorados). Esta ferramenta NUNCA escreve: valide o patch a seco com validate_config, aplique-o só após confirmação do utilizador e lembre-se de que a ativação continua sujeita ao fluxo de aprovação humana. Puro e offline.',
		ja: '能力の不足を自由記述(need)で説明すると、最大 3 件のカタログ候補(各 1 行の根拠付き)と、それらを外部サーバー設定に追加する RFC 6902 JSON パッチが得られます(バージョン固定、環境変数の名前のみ、宣言済みの id はスキップ)。このツールは決して書き込みません:validate_config でパッチを空実行し、ユーザーの確認後にのみ適用してください。有効化は依然として人間の承認フローで制御される点に注意。純粋かつオフライン。',
		zh: '用自由文本(need)描述能力缺口,即可获得最多 3 个目录候选项(每个附一行理由),以及一个将它们添加到外部服务器配置的 RFC 6902 JSON 补丁(固定版本、仅环境变量名称;已声明的 id 会被跳过)。此工具绝不写入:用 validate_config 对补丁进行空跑,仅在用户确认后应用,并记住激活仍受人工确认流程约束。纯粹且离线。',
		hi: 'क्षमता की कमी को मुक्त पाठ (need) में बताएँ और अधिकतम 3 सूची उम्मीदवार पाएँ, प्रत्येक एक-पंक्ति औचित्य के साथ, साथ ही एक RFC 6902 JSON पैच जो उन्हें बाहरी-सर्वर कॉन्फ़िग में जोड़ता है (पिन किए गए संस्करण, केवल पर्यावरण चर के नाम; पहले से घोषित ids छोड़ दिए जाते हैं)। यह उपकरण कभी नहीं लिखता: validate_config से पैच को ड्राई-रन करें, उपयोगकर्ता की पुष्टि पर ही लागू करें, और याद रखें कि सक्रियण अभी भी मानव अनुमोदन प्रवाह से नियंत्रित है। शुद्ध और ऑफ़लाइन।',
		ar: 'صف فجوة قدرة بنص حر (need) واحصل على ما يصل إلى 3 مرشحين من الفهرس، لكل منهم مبرّر من سطر واحد، بالإضافة إلى تصحيح JSON وفق RFC 6902 يُضيفهم إلى إعداد الخوادم الخارجية (إصدارات مثبّتة، أسماء متغيرات بيئة فقط؛ ويتم تخطّي المعرّفات المعلَنة سلفًا). هذه الأداة لا تكتب أبدًا: شغّل التصحيح تجريبيًا بـ validate_config، ولا تطبّقه إلا بتأكيد المستخدم، وتذكّر أن التفعيل يبقى محكومًا بمسار الموافقة البشرية. نقي وبدون اتصال.',
		th: 'อธิบายช่องว่างความสามารถเป็นข้อความอิสระ (need) แล้วรับผู้สมัครจากแคตตาล็อกสูงสุด 3 รายการ พร้อมเหตุผลบรรทัดเดียวต่อรายการ และแพตช์ JSON ตาม RFC 6902 ที่เพิ่มรายการเหล่านั้นเข้าในการตั้งค่าเซิร์ฟเวอร์ภายนอก (เวอร์ชันที่ตรึงไว้ ชื่อตัวแปรสภาพแวดล้อมเท่านั้น; ข้าม id ที่ประกาศไว้แล้ว) เครื่องมือนี้ไม่เขียนเด็ดขาด: ทดสอบแพตช์แบบไม่เขียนจริงด้วย validate_config ใช้เมื่อผู้ใช้ยืนยันเท่านั้น และจำไว้ว่าการเปิดใช้งานยังถูกควบคุมด้วยกระบวนการอนุมัติของมนุษย์ บริสุทธิ์และออฟไลน์',
		vi: 'Mô tả khoảng thiếu năng lực bằng văn bản tự do (need) và nhận tối đa 3 ứng viên từ danh mục, mỗi ứng viên kèm lý do một dòng, cùng một bản vá JSON RFC 6902 THÊM chúng vào cấu hình máy chủ ngoài (phiên bản đã ghim, chỉ TÊN biến môi trường; bỏ qua các id đã khai báo). Công cụ này KHÔNG bao giờ ghi: chạy thử bản vá bằng validate_config, chỉ áp dụng khi người dùng xác nhận, và nhớ rằng việc kích hoạt vẫn bị kiểm soát bởi luồng phê duyệt của con người. Thuần túy và ngoại tuyến.',
	},
};
