// i18n catalogue for `delendai_external-mcps_validate_config`.
//
// Per-tool i18n entry (f00068 S4). The 12-lang invariant is enforced by
// `check-i18n.ts` once the entry opts in via `apps/web/src/i18n/tools/index.ts`.

import type { IToolI18n } from '#I18N/tools/_shape';

export const externalMcpsValidateConfigI18n: IToolI18n = {
	description: {
		en: 'Dry-run a proposed external-servers config block against the Zod schema without writing or booting anything. Enforces mandatory exact version pins (rejects "latest"), kebab-case server ids, and env entries that are variable NAMES only (never cleartext secrets). Returns a structured list of issues with stable codes so the LLM can fix them on the spot. Pure and offline.',
		es: 'Valida en seco un bloque de configuración propuesto de servidores externos contra el esquema Zod sin escribir ni arrancar nada. Exige fijaciones de versión exactas obligatorias (rechaza "latest"), ids de servidor en kebab-case y entradas de entorno que sean solo NOMBRES de variables (nunca secretos en texto claro). Devuelve una lista estructurada de problemas con códigos estables para que el LLM los corrija al momento. Puro y sin conexión.',
		fr: 'Valide à blanc un bloc de configuration de serveurs externes proposé contre le schéma Zod sans rien écrire ni démarrer. Impose des versions épinglées exactes obligatoires (rejette « latest »), des ids de serveur en kebab-case et des entrées d’environnement qui ne sont que des NOMS de variables (jamais de secrets en clair). Renvoie une liste structurée de problèmes avec des codes stables pour que le LLM les corrige immédiatement. Pur et hors ligne.',
		de: 'Führt einen Trockenlauf eines vorgeschlagenen Konfigurationsblocks für externe Server gegen das Zod-Schema aus, ohne etwas zu schreiben oder zu starten. Erzwingt verpflichtende exakte Versions-Pins (lehnt "latest" ab), kebab-case Server-IDs und Umgebungseinträge, die nur Variablen-NAMEN sind (nie Klartext-Geheimnisse). Gibt eine strukturierte Liste von Problemen mit stabilen Codes zurück, damit das LLM sie sofort beheben kann. Rein und offline.',
		it: 'Esegue una validazione a secco di un blocco di configurazione di server esterni proposto rispetto allo schema Zod senza scrivere né avviare nulla. Impone pin di versione esatti obbligatori (rifiuta "latest"), id di server in kebab-case e voci d’ambiente che siano solo NOMI di variabili (mai segreti in chiaro). Restituisce un elenco strutturato di problemi con codici stabili così che l’LLM li corregga subito. Puro e offline.',
		pt: 'Executa uma validação a seco de um bloco de configuração de servidores externos proposto contra o esquema Zod sem escrever nem arrancar nada. Exige fixações de versão exatas obrigatórias (rejeita "latest"), ids de servidor em kebab-case e entradas de ambiente que sejam apenas NOMES de variáveis (nunca segredos em texto simples). Devolve uma lista estruturada de problemas com códigos estáveis para o LLM os corrigir de imediato. Puro e offline.',
		ja: '提案された外部サーバー設定ブロックを、何も書き込まず何も起動せずに Zod スキーマで空実行(ドライラン)検証します。必須の厳密なバージョン固定(「latest」を拒否)、kebab-case のサーバー ID、環境エントリが変数名のみ(平文のシークレットは不可)であることを強制します。安定したコード付きの構造化された問題一覧を返し、LLM がその場で修正できます。純粋かつオフライン。',
		zh: '针对 Zod 模式对提议的外部服务器配置块进行空跑校验,不写入也不启动任何东西。强制要求必需的精确版本固定(拒绝 "latest")、kebab-case 的服务器 id,以及仅为变量名称的环境条目(绝不含明文密钥)。返回带稳定代码的结构化问题列表,便于 LLM 当场修复。纯粹且离线。',
		hi: 'प्रस्तावित बाहरी-सर्वर कॉन्फ़िग ब्लॉक को Zod स्कीमा के विरुद्ध बिना कुछ लिखे या बूट किए ड्राई-रन सत्यापित करता है। अनिवार्य सटीक संस्करण पिन ("latest" अस्वीकृत), kebab-case सर्वर ids, और केवल चर के नाम वाली पर्यावरण प्रविष्टियाँ (कभी स्पष्ट-पाठ रहस्य नहीं) लागू करता है। स्थिर कोड के साथ समस्याओं की संरचित सूची लौटाता है ताकि LLM उन्हें तुरंत ठीक कर सके। शुद्ध और ऑफ़लाइन।',
		ar: 'يُجري تشغيلًا تجريبيًا لكتلة إعداد خوادم خارجية مقترحة مقابل مخطط Zod دون كتابة أو تشغيل أي شيء. يفرض تثبيت إصدارات دقيقة إلزامية (يرفض "latest")، ومعرّفات خوادم بصيغة kebab-case، ومدخلات بيئة تكون أسماء متغيرات فقط (لا أسرار بنص واضح أبدًا). يعيد قائمة منظّمة بالمشكلات مع رموز ثابتة كي يصلحها النموذج في الحال. نقي وبدون اتصال.',
		th: 'ทดสอบแบบไม่เขียนจริงต่อบล็อกการตั้งค่าเซิร์ฟเวอร์ภายนอกที่เสนอ เทียบกับสคีมา Zod โดยไม่เขียนหรือบูตสิ่งใด บังคับให้ตรึงเวอร์ชันแบบเป๊ะที่จำเป็น (ปฏิเสธ "latest"), id เซิร์ฟเวอร์แบบ kebab-case และรายการสภาพแวดล้อมที่เป็นชื่อตัวแปรเท่านั้น (ไม่มีความลับแบบข้อความธรรมดา) คืนรายการปัญหาแบบมีโครงสร้างพร้อมรหัสคงที่ เพื่อให้ LLM แก้ไขได้ทันที บริสุทธิ์และออฟไลน์',
		vi: 'Chạy thử một khối cấu hình máy chủ ngoài được đề xuất theo lược đồ Zod mà không ghi hay khởi động bất cứ thứ gì. Bắt buộc ghim phiên bản chính xác (từ chối "latest"), id máy chủ kiểu kebab-case, và các mục môi trường chỉ là TÊN biến (không bao giờ là bí mật dạng văn bản thô). Trả về danh sách vấn đề có cấu trúc kèm mã ổn định để LLM sửa ngay. Thuần túy và ngoại tuyến.',
	},
};
