// i18n catalogue for `delendai_external-mcps_ack`.
//
// Per-tool i18n entry (f00068 S4). The 12-lang invariant is enforced by
// `check-i18n.ts` once the entry opts in via `apps/web/src/i18n/tools/index.ts`.

import type { IToolI18n } from '#I18N/tools/_shape';

export const externalMcpsAckI18n: IToolI18n = {
	description: {
		en: 'Record or list human acknowledgements for LLM-decided external-server activation. Pass list:true to see pending requests, or {server, accept} to record an accept/reject. Decisions are durable, redacted before writing, and one entry per server; a server stays blocked from activation until it has an accepted ack. This is the human gate behind requireHumanAckWhenLlmDecides.',
		es: 'Registra o lista las aprobaciones humanas para la activación de servidores externos decidida por el LLM. Pasa list:true para ver las solicitudes pendientes, o {server, accept} para registrar una aceptación/rechazo. Las decisiones son duraderas, se redactan antes de escribir y hay una entrada por servidor; un servidor sigue bloqueado para la activación hasta tener una aprobación aceptada. Esta es la puerta humana tras requireHumanAckWhenLlmDecides.',
		fr: 'Enregistre ou liste les validations humaines pour l’activation de serveurs externes décidée par le LLM. Passez list:true pour voir les demandes en attente, ou {server, accept} pour enregistrer une acceptation/un refus. Les décisions sont durables, expurgées avant écriture, avec une entrée par serveur ; un serveur reste bloqué à l’activation tant qu’il n’a pas de validation acceptée. C’est le verrou humain derrière requireHumanAckWhenLlmDecides.',
		de: 'Erfasst oder listet menschliche Bestätigungen für die vom LLM entschiedene Aktivierung externer Server. Übergib list:true, um ausstehende Anfragen zu sehen, oder {server, accept}, um eine Annahme/Ablehnung zu erfassen. Entscheidungen sind dauerhaft, werden vor dem Schreiben redigiert, ein Eintrag pro Server; ein Server bleibt von der Aktivierung gesperrt, bis er eine akzeptierte Bestätigung hat. Dies ist das menschliche Tor hinter requireHumanAckWhenLlmDecides.',
		it: 'Registra o elenca le approvazioni umane per l’attivazione di server esterni decisa dall’LLM. Passa list:true per vedere le richieste in sospeso, o {server, accept} per registrare un’accettazione/rifiuto. Le decisioni sono durature, oscurate prima della scrittura, una voce per server; un server resta bloccato dall’attivazione finché non ha un’approvazione accettata. Questo è il cancello umano dietro requireHumanAckWhenLlmDecides.',
		pt: 'Regista ou lista as aprovações humanas para a ativação de servidores externos decidida pelo LLM. Passe list:true para ver os pedidos pendentes, ou {server, accept} para registar uma aceitação/rejeição. As decisões são duráveis, redigidas antes de escrever e uma entrada por servidor; um servidor permanece bloqueado para ativação até ter uma aprovação aceite. Este é o portão humano por trás de requireHumanAckWhenLlmDecides.',
		ja: 'LLM が決定した外部サーバーの有効化に対する人間の承認を記録または一覧します。list:true で保留中の要求を確認し、{server, accept} で承認/却下を記録します。決定は永続化され、書き込み前に秘匿化され、サーバーごとに 1 エントリです。サーバーは承認済みの ack を得るまで有効化がブロックされます。これは requireHumanAckWhenLlmDecides の背後にある人間のゲートです。',
		zh: '记录或列出针对 LLM 决定的外部服务器激活的人工确认。传入 list:true 查看待处理请求,或传入 {server, accept} 记录接受/拒绝。决定是持久的,写入前会脱敏,每个服务器一条记录;在获得已接受的确认之前,服务器的激活始终被阻止。这是 requireHumanAckWhenLlmDecides 背后的人工关卡。',
		hi: 'LLM द्वारा तय बाहरी-सर्वर सक्रियण के लिए मानव अनुमोदन दर्ज करें या सूचीबद्ध करें। लंबित अनुरोध देखने के लिए list:true पास करें, या स्वीकृति/अस्वीकृति दर्ज करने के लिए {server, accept}। निर्णय स्थायी होते हैं, लिखने से पहले संपादित (redacted) होते हैं, और प्रति सर्वर एक प्रविष्टि; एक सर्वर तब तक सक्रियण से अवरुद्ध रहता है जब तक उसके पास स्वीकृत ack न हो। यह requireHumanAckWhenLlmDecides के पीछे का मानव द्वार है।',
		ar: 'يسجّل أو يسرد الموافقات البشرية على تفعيل خادم خارجي قرّره النموذج. مرّر list:true لعرض الطلبات المعلّقة، أو {server, accept} لتسجيل قبول/رفض. القرارات دائمة، وتُنقّح قبل الكتابة، ومدخل واحد لكل خادم؛ ويبقى الخادم محظورًا من التفعيل حتى تكون لديه موافقة مقبولة. هذه هي البوابة البشرية خلف requireHumanAckWhenLlmDecides.',
		th: 'บันทึกหรือแสดงรายการการอนุมัติของมนุษย์สำหรับการเปิดใช้งานเซิร์ฟเวอร์ภายนอกที่ LLM ตัดสินใจ ส่ง list:true เพื่อดูคำขอที่ค้างอยู่ หรือ {server, accept} เพื่อบันทึกการยอมรับ/ปฏิเสธ การตัดสินใจมีความคงทน ถูกปิดบังก่อนเขียน และหนึ่งรายการต่อเซิร์ฟเวอร์; เซิร์ฟเวอร์จะถูกบล็อกจากการเปิดใช้งานจนกว่าจะมี ack ที่ยอมรับแล้ว นี่คือด่านมนุษย์ที่อยู่เบื้องหลัง requireHumanAckWhenLlmDecides',
		vi: 'Ghi hoặc liệt kê các phê duyệt của con người cho việc kích hoạt máy chủ ngoài do LLM quyết định. Truyền list:true để xem các yêu cầu đang chờ, hoặc {server, accept} để ghi một chấp nhận/từ chối. Quyết định có tính bền vững, được ẩn thông tin nhạy cảm trước khi ghi, và mỗi máy chủ một mục; một máy chủ vẫn bị chặn kích hoạt cho đến khi có một ack được chấp nhận. Đây là cổng con người phía sau requireHumanAckWhenLlmDecides.',
	},
};
