// i18n catalogue for `mcp-vertex_external-mcps_catalog`.
//
// Per-tool i18n entry (f00068 S4). The 12-lang invariant is enforced by
// `check-i18n.ts` once the entry opts in via `apps/web/src/i18n/tools/index.ts`.

import type { IToolI18n } from '#I18N/tools/_shape';

export const externalMcpsCatalogI18n: IToolI18n = {
	description: {
		en: 'Search the curated + discoverable catalog of composable third-party MCP servers. Compact by default: up to 10 {id, category, summary} rows plus a total count — narrow the query when total exceeds 10. Pass detail:<id> for one full entry (tier, pinned install command/args, required env var NAMES). Entries matched by a workspace probe carry detected:true — a hint only; it never activates a server. Read-only and offline.',
		es: 'Busca en el catálogo curado + descubrible de servidores MCP de terceros componibles. Compacto por defecto: hasta 10 filas {id, categoría, resumen} más un recuento total; afina la consulta cuando el total supere 10. Pasa detail:<id> para una entrada completa (nivel, comando/args de instalación fijados, NOMBRES de variables de entorno requeridas). Las entradas detectadas por una sonda del espacio de trabajo llevan detected:true, solo una pista; nunca activa un servidor. Solo lectura y sin conexión.',
		fr: 'Recherche dans le catalogue curé + découvrable de serveurs MCP tiers composables. Compact par défaut : jusqu’à 10 lignes {id, catégorie, résumé} plus un total — affinez la requête quand le total dépasse 10. Passez detail:<id> pour une entrée complète (palier, commande/args d’installation épinglés, NOMS des variables d’environnement requises). Les entrées repérées par une sonde de l’espace de travail portent detected:true — un simple indice ; cela n’active jamais un serveur. Lecture seule et hors ligne.',
		de: 'Durchsucht den kuratierten + auffindbaren Katalog komponierbarer Drittanbieter-MCP-Server. Standardmäßig kompakt: bis zu 10 {id, Kategorie, Zusammenfassung}-Zeilen plus eine Gesamtzahl — verfeinere die Abfrage, wenn total 10 übersteigt. Übergib detail:<id> für einen vollständigen Eintrag (Stufe, gepinnter Installationsbefehl/Args, benötigte Umgebungsvariablen-NAMEN). Von einer Workspace-Prüfung erkannte Einträge tragen detected:true — nur ein Hinweis; es aktiviert nie einen Server. Nur lesend und offline.',
		it: 'Cerca nel catalogo curato + individuabile di server MCP di terze parti componibili. Compatto per default: fino a 10 righe {id, categoria, riepilogo} più un conteggio totale — restringi la query quando il totale supera 10. Passa detail:<id> per una voce completa (livello, comando/args di installazione fissati, NOMI delle variabili d’ambiente richieste). Le voci individuate da una sonda del workspace portano detected:true — solo un suggerimento; non attiva mai un server. Sola lettura e offline.',
		pt: 'Pesquisa no catálogo curado + descobrível de servidores MCP de terceiros componíveis. Compacto por padrão: até 10 linhas {id, categoria, resumo} mais uma contagem total — refine a consulta quando o total exceder 10. Passe detail:<id> para uma entrada completa (nível, comando/args de instalação fixados, NOMES das variáveis de ambiente necessárias). Entradas detetadas por uma sonda do espaço de trabalho levam detected:true — apenas uma dica; nunca ativa um servidor. Só de leitura e offline.',
		ja: '合成可能なサードパーティ MCP サーバーの「厳選+発見可能」カタログを検索します。既定でコンパクト:最大 10 件の {id, カテゴリ, 要約} 行と総数を返します。総数が 10 を超えたらクエリを絞り込みます。detail:<id> で 1 件の完全なエントリ(ティア、ピン留めしたインストールコマンド/引数、必要な環境変数の名前)を取得します。ワークスペースのプローブが一致したエントリには detected:true が付きます——これはヒントのみで、サーバーを起動することはありません。読み取り専用かつオフライン。',
		zh: '搜索可组合的第三方 MCP 服务器的精选 + 可发现目录。默认紧凑:最多 10 行 {id、类别、摘要} 加上总数;当总数超过 10 时缩小查询范围。传入 detail:<id> 获取一条完整条目(层级、固定的安装命令/参数、所需环境变量名称)。被工作区探测命中的条目带有 detected:true——仅为提示,绝不激活服务器。只读且离线。',
		hi: 'संयोजनीय तृतीय-पक्ष MCP सर्वरों की क्यूरेटेड + खोज-योग्य सूची में खोजें। डिफ़ॉल्ट रूप से संक्षिप्त: अधिकतम 10 {id, श्रेणी, सारांश} पंक्तियाँ और एक कुल गिनती — जब कुल 10 से अधिक हो तो क्वेरी संकीर्ण करें। एक पूर्ण प्रविष्टि के लिए detail:<id> पास करें (स्तर, पिन किया गया इंस्टॉल कमांड/args, आवश्यक पर्यावरण चर के नाम)। वर्कस्पेस जाँच से मिली प्रविष्टियों पर detected:true होता है — केवल एक संकेत; यह कभी सर्वर सक्रिय नहीं करता। केवल पढ़ने के लिए और ऑफ़लाइन।',
		ar: 'ابحث في الفهرس المنسَّق + القابل للاكتشاف لخوادم MCP الخارجية القابلة للتركيب. مضغوط افتراضيًا: حتى 10 صفوف {المعرّف، الفئة، الملخّص} مع عدد إجمالي — ضيّق الاستعلام عندما يتجاوز الإجمالي 10. مرّر detail:<id> للحصول على مدخل كامل واحد (الطبقة، أمر/وسائط التثبيت المثبّتة، أسماء متغيرات البيئة المطلوبة). المدخلات التي طابقها فحص مساحة العمل تحمل detected:true — مجرّد تلميح؛ ولا تُفعّل خادمًا أبدًا. للقراءة فقط وبدون اتصال.',
		th: 'ค้นหาแคตตาล็อกที่คัดสรร + ค้นพบได้ของเซิร์ฟเวอร์ MCP บุคคลที่สามที่ประกอบได้ กะทัดรัดโดยค่าเริ่มต้น: สูงสุด 10 แถว {id, หมวดหมู่, สรุป} พร้อมจำนวนรวม — จำกัดคำค้นเมื่อจำนวนรวมเกิน 10 ส่ง detail:<id> เพื่อรับรายการเต็มหนึ่งรายการ (ระดับ, คำสั่ง/อาร์กิวเมนต์การติดตั้งที่ตรึงไว้, ชื่อตัวแปรสภาพแวดล้อมที่จำเป็น) รายการที่ตรงกับการตรวจสอบพื้นที่ทำงานจะมี detected:true — เป็นเพียงคำใบ้ ไม่เคยเปิดใช้งานเซิร์ฟเวอร์ อ่านอย่างเดียวและออฟไลน์',
		vi: 'Tìm trong danh mục được tuyển chọn + có thể khám phá của các máy chủ MCP bên thứ ba có thể kết hợp. Gọn nhẹ theo mặc định: tối đa 10 hàng {id, danh mục, tóm tắt} kèm tổng số — thu hẹp truy vấn khi tổng vượt quá 10. Truyền detail:<id> để lấy một mục đầy đủ (bậc, lệnh/tham số cài đặt đã ghim, TÊN biến môi trường bắt buộc). Các mục được một phép dò không gian làm việc khớp sẽ mang detected:true — chỉ là gợi ý; nó không bao giờ kích hoạt máy chủ. Chỉ đọc và ngoại tuyến.',
	},
};
