/**
 * `apps/shared/src/components/ui/code-block.ts` — host-agnostic
 * code block, returns the figure element as a string.
 *
 * Replaces the markup portion of
 * `apps/web/src/components/ui/CodeBlock.astro` (f00048 S1) — the docs
 * site and any future product surface (extension webviews,
 * JetBrains, etc.) emit the exact same HTML. The companion SCSS
 * (`apps/shared/src/styles/components/_code.scss`) carries the BEM
 * rules, with a trailing `@extend` alias for the legacy `.ui-code*`
 * selectors so the docs site's existing markup keeps working until
 * the rename lands.
 *
 * Conventions
 * -----------
 * - The copy button is rendered as `<button data-copy-target="...">`
 *     The host injects the runtime glue (from `renderRuntime` or the
 *     equivalent in
 *     `apps/web/src/components/ui/_code-copy-controller.ts`) that
 *     wires `data-copy-target` to the matching `<code id>` and
 *     toggles `data-state="copied"`. The renderer just emits the
 *     markup.
 * - The `<code>` content is escaped (HTML-special characters
 *     become entities) so the caller can pass raw source.
 * - Class namespace: `mcpv-code`, `mcpv-code__*`, `mcpv-code--inline`.
 * - `id` on the `<code>` is auto-generated by a monotonic per-pass
 *     counter (a00069): every block gets a GUARANTEED-unique id, so two
 *     blocks on one page can never collide (duplicate DOM ids are invalid
 *     HTML and would make the copy button target the wrong block). The
 *     old `Math.random()` suffix could collide and, despite the docstring
 *     claiming determinism, was non-deterministic. Callers may still
 *     override with `id`. A host that wants ids to be stable across
 *     builds (e.g. for HTML diff tooling) calls {@link resetCodeBlockIds}
 *     at the start of each page render, so every page reproduces the same
 *     `cb-1, cb-2, …` sequence deterministically.
 */
import { escapeHtml } from '../../lib/escape';

export interface ICodeBlockProps {
	readonly code: string;
	readonly lang?: string;
	readonly filename?: string;
	readonly caption?: string;
	/** Defaults to `true`. Set to `false` to omit the copy button. */
	readonly showCopy?: boolean;
	/** When `true`, the figure renders as a single-line inline chip. */
	readonly inline?: boolean;
	/**
	 * Accessible label for the copy button. When omitted, hosts can
	 * supply their own i18n lookup via the surrounding runtime
	 * glue (the default id-keyed label is "Copy" in EN / "Copiar"
	 * in ES, picked by the runtime).
	 */
	readonly copyLabel?: string;
	/**
	 * Optional override of the auto-generated `<code id>`. Most
	 * callers can leave this off.
	 */
	readonly id?: string;
}

// a00069: monotonic per-pass counter → every auto id is unique. A host
// resets it (see `resetCodeBlockIds`) at the start of a render pass so a
// given page reproduces the same ids across builds (stable HTML diffs).
let idCounter = 0;
const nextCodeBlockId = (): string => {
	idCounter += 1;
	return `cb-${idCounter.toString(36)}`;
};

/**
 * Reset the auto-`id` counter. Call at the start of each SSR page render
 * so every page yields a deterministic `cb-1, cb-2, …` sequence (unique
 * within the page, identical across builds). Optional: without it, ids
 * stay unique but simply keep counting up across the whole build.
 */
export const resetCodeBlockIds = (): void => {
	idCounter = 0;
};

const renderHead = (
	lang: string,
	filename: string | undefined,
	caption: string | undefined,
	showCopy: boolean,
	id: string,
	copyLabel: string,
): string => {
	if (!filename && !lang && !caption && !showCopy) return '';

	const headL =
		filename || (!filename && lang) || caption
			? `<div class="mcpv-code__head-l">` +
				(filename
					? `<span class="mcpv-code__file">${escapeHtml(filename)}</span>`
					: '') +
				(!filename && lang
					? `<span class="mcpv-code__lang">${escapeHtml(lang)}</span>`
					: '') +
				(caption
					? `<span class="mcpv-code__caption">${escapeHtml(caption)}</span>`
					: '') +
				`</div>`
			: '';

	const copy = showCopy
		? `<button type="button" class="mcpv-code__copy" data-copy-target="${escapeHtml(id)}" ` +
			`aria-label="${escapeHtml(copyLabel)}">` +
			`<span class="mcpv-code__copy-text" data-copy-label="idle">${escapeHtml(copyLabel)}</span>` +
			`</button>`
		: '';

	return `<header class="mcpv-code__head">${headL}${copy}</header>`;
};

/**
 * Render a `<figure class="mcpv-code">` code block as a string.
 *
 * @example
 *   renderCodeBlock({
 *     code: 'export const x = 1;\n',
 *     lang: 'ts',
 *     filename: 'index.ts',
 *     copyLabel: 'Copy'
 *   })
 */
export const renderCodeBlock = (props: ICodeBlockProps): string => {
	const code = props.code;
	const lang = props.lang ?? 'text';
	const filename = props.filename;
	const caption = props.caption;
	const showCopy = props.showCopy ?? true;
	const inline = props.inline ?? false;
	const id = props.id ?? nextCodeBlockId();
	const copyLabel = props.copyLabel ?? 'Copy';

	const cls = inline ? 'mcpv-code mcpv-code--inline' : 'mcpv-code';

	return (
		`<figure class="${cls}" data-lang="${escapeHtml(lang)}">` +
		renderHead(lang, filename, caption, showCopy, id, copyLabel) +
		`<pre class="mcpv-code__pre"><code id="${escapeHtml(id)}" class="language-${escapeHtml(lang)}">${escapeHtml(code)}</code></pre>` +
		`</figure>`
	);
};
