export const GENERATED_WEB_PLUGIN_CATALOG =
[
	{
		"slug": "adaptive-optimizer",
		"displayName": "Adaptive Optimizer",
		"purpose": "Adaptive optimizer: cheaply rank model, plugin-set and prompt candidates with explicit budget and consent guards.",
		"category": "code-intelligence"
	},
	{
		"slug": "agent-orchestrator",
		"displayName": "Agent Orchestrator",
		"purpose": "Workflow policy plugin: single / linear / swarm / auto modes with token budgets, iteration caps, and mid-task subagent rotation.",
		"category": "workflow"
	},
	{
		"slug": "api",
		"displayName": "Api",
		"purpose": "REST/GraphQL API surface for delendai plugins.",
		"category": "integration"
	},
	{
		"slug": "audit",
		"displayName": "Audit",
		"purpose": "Multi-model audit planning + consolidation; f00139 adds self_audit dogfood loop.",
		"category": "integration"
	},
	{
		"slug": "audit-orchestrator",
		"displayName": "Audit Orchestrator",
		"purpose": "Orchestrates implementation work generated by project-agnostic audit plan proposals.",
		"category": "workflow"
	},
	{
		"slug": "auto-agent-selector",
		"displayName": "Auto Agent Selector",
		"purpose": "Zero-config multi-agent routing (cost↔quality dial, auto_recommend, escalation).",
		"category": "integration"
	},
	{
		"slug": "auto-plugin-selector",
		"displayName": "Auto Plugin Selector",
		"purpose": "Recommends the best plugin set for this project from its signals (manifest, files, git, task).",
		"category": "code-intelligence"
	},
	{
		"slug": "browser",
		"displayName": "Browser",
		"purpose": "Headless browser automation tools.",
		"category": "integration"
	},
	{
		"slug": "cache",
		"displayName": "Cache",
		"purpose": "Cache-eviction rules and lifecycle for plugin scratch dirs.",
		"category": "observability"
	},
	{
		"slug": "commit-policy",
		"displayName": "Commit Policy",
		"purpose": "Commit-authority plugin: configurable identity, cadence and audit-trail policy wrapping the git plugin primitives. Off by default — opt in via plugins.commit-policy.options.",
		"category": "code-intelligence"
	},
	{
		"slug": "completion",
		"displayName": "Completion",
		"purpose": "Task-completion notifier: records an agent declaring its original task done + reviewed and pushes a notification.",
		"category": "workflow"
	},
	{
		"slug": "container",
		"displayName": "Container",
		"purpose": "Container inspection + lint (docker ps/images, k8s, Dockerfile rules).",
		"category": "integration"
	},
	{
		"slug": "context-for-change",
		"displayName": "Context For Change",
		"purpose": "Compact task-oriented change context orchestration across diff, symbols, tests, docs and conventions.",
		"category": "code-intelligence"
	},
	{
		"slug": "conventions",
		"displayName": "Conventions",
		"purpose": "Repo file-convention enforcement (interface, constant, service, tool …).",
		"category": "code-intelligence"
	},
	{
		"slug": "database",
		"displayName": "Database",
		"purpose": "Database schema/introspection tools (read-only, offline).",
		"category": "integration"
	},
	{
		"slug": "deps",
		"displayName": "Deps",
		"purpose": "Dependency inventory + offline health (deps_list, deps_check, deps_audit, deps_licenses, deps_tree).",
		"category": "integration"
	},
	{
		"slug": "diagram",
		"displayName": "Diagram",
		"purpose": "Diagram generator (mermaid, dot) from code structure.",
		"category": "knowledge"
	},
	{
		"slug": "docs",
		"displayName": "Docs",
		"purpose": "Doc generation, search, and rendered catalog.",
		"category": "knowledge"
	},
	{
		"slug": "env",
		"displayName": "Env",
		"purpose": "Environment config validation (.env check + schema + env_explains).",
		"category": "code-intelligence"
	},
	{
		"slug": "error-reporting",
		"displayName": "Error Reporting",
		"purpose": "Automatic delendai error reporting: opens de-duplicated GitHub issues for internal failures after explicit opt-in.",
		"category": "integration"
	},
	{
		"slug": "external-mcps",
		"displayName": "External Mcps",
		"purpose": "Compose third-party MCP servers through the catalog + human ack.",
		"category": "integration"
	},
	{
		"slug": "forge",
		"displayName": "Forge",
		"purpose": "Forge (GitHub/GitLab) wrappers — PRs, CI, issues.",
		"category": "integration"
	},
	{
		"slug": "git",
		"displayName": "Git",
		"purpose": "Git wrappers (PR list/view, diff, changelog, extended).",
		"category": "code-intelligence"
	},
	{
		"slug": "github",
		"displayName": "Github",
		"purpose": "GitHub read-only provider context, HTTP client and remote resource tools.",
		"category": "integration"
	},
	{
		"slug": "gitlab",
		"displayName": "Gitlab",
		"purpose": "GitLab read-only provider context, HTTP client and resource tools.",
		"category": "integration"
	},
	{
		"slug": "i18n",
		"displayName": "I18n",
		"purpose": "i18n key/interpolation validation across locale JSON files.",
		"category": "code-intelligence"
	},
	{
		"slug": "impact-analysis",
		"displayName": "Impact Analysis",
		"purpose": "Bounded impact analysis and test selection across changed symbols, dependents and related specs.",
		"category": "quality"
	},
	{
		"slug": "issues",
		"displayName": "Issues",
		"purpose": "Issue tracker (GitHub) integration — list/fetch/analyze/ingest/resolve.",
		"category": "integration"
	},
	{
		"slug": "link-check",
		"displayName": "Link Check",
		"purpose": "Markdown link checker.",
		"category": "knowledge"
	},
	{
		"slug": "logs",
		"displayName": "Logs",
		"purpose": "Structured logs reader (tail, query, redact).",
		"category": "observability"
	},
	{
		"slug": "memory",
		"displayName": "Memory",
		"purpose": "Persistent memory store (BM25 + recall, save, search).",
		"category": "knowledge"
	},
	{
		"slug": "notification",
		"displayName": "Notification",
		"purpose": "Notification + lock-await primitives.",
		"category": "workflow"
	},
	{
		"slug": "observability",
		"displayName": "Observability",
		"purpose": "Observability surface (metrics, errors, telemetry).",
		"category": "observability"
	},
	{
		"slug": "orchestrator-runner",
		"displayName": "Orchestrator Runner",
		"purpose": "Orchestrator-runner runtime utilities.",
		"category": "integration"
	},
	{
		"slug": "perf",
		"displayName": "Perf",
		"purpose": "Performance bench/bundle/profile tools.",
		"category": "observability"
	},
	{
		"slug": "project-health",
		"displayName": "Project Health",
		"purpose": "Compact project-health aggregator: cheap summary first, lazy domain details on demand.",
		"category": "code-intelligence"
	},
	{
		"slug": "project-kpis",
		"displayName": "Project Kpis",
		"purpose": "Versioned project KPI snapshots and observability views across health, usage, economics and delivery.",
		"category": "observability"
	},
	{
		"slug": "prompt-eval",
		"displayName": "Prompt Eval",
		"purpose": "Prompt-eval harness (golden prompts, scoring).",
		"category": "knowledge"
	},
	{
		"slug": "prompts-pack",
		"displayName": "Prompts Pack",
		"purpose": "Project-aware MCP prompts (explain-this-code, write-tests-for, review-this-diff, etc.).",
		"category": "knowledge"
	},
	{
		"slug": "proposals",
		"displayName": "Proposals",
		"purpose": "Proposals workflow + multi-agent (swarm) orchestration.",
		"category": "workflow"
	},
	{
		"slug": "quality",
		"displayName": "Quality",
		"purpose": "Quality gates: coverage, complexity, lint, type-check orchestration.",
		"category": "quality"
	},
	{
		"slug": "quality-policy",
		"displayName": "Quality Policy",
		"purpose": "Unified quality-policy surface: cheap tests, conventions, lint, types and coverage guidance without running heavy quality commands.",
		"category": "quality"
	},
	{
		"slug": "refactor",
		"displayName": "Refactor",
		"purpose": "Refactor primitives (symbols, definition, references, rename, codemod).",
		"category": "code-intelligence"
	},
	{
		"slug": "remote-provider-core",
		"displayName": "Remote Provider Core",
		"purpose": "Shared remote-provider foundation: validated config, injectable HTTP, normalized errors.",
		"category": "code-intelligence"
	},
	{
		"slug": "rules",
		"displayName": "Rules",
		"purpose": "Lint/type rules engine (frameworks, dogmas, presets).",
		"category": "quality"
	},
	{
		"slug": "search",
		"displayName": "Search",
		"purpose": "Code search (semantic + symbol + references).",
		"category": "code-intelligence"
	},
	{
		"slug": "security",
		"displayName": "Security",
		"purpose": "Security audit (CVEs, SAST, secrets, env).",
		"category": "quality"
	},
	{
		"slug": "skills-pack",
		"displayName": "Skills Pack",
		"purpose": "Curated skill pack (debugging, perf, pr-review, security, incident, migration).",
		"category": "knowledge"
	},
	{
		"slug": "status-marker",
		"displayName": "Status Marker",
		"purpose": "Status marker + closure canonical line.",
		"category": "code-intelligence"
	},
	{
		"slug": "tech-debt",
		"displayName": "Tech Debt",
		"purpose": "Tech-debt scanner (TODO/FIXME/HACK inventory).",
		"category": "quality"
	},
	{
		"slug": "test-convention",
		"displayName": "Test Convention",
		"purpose": "Test-file convention enforcement (spec path, mock style, forbidden patterns).",
		"category": "quality"
	},
	{
		"slug": "test-policy",
		"displayName": "Test Policy",
		"purpose": "Test policy mode (TDD, tests-after, free, none).",
		"category": "quality"
	},
	{
		"slug": "usage-tracking",
		"displayName": "Usage Tracking",
		"purpose": "Per-token/per-call usage tracking (spend, budget).",
		"category": "observability"
	},
	{
		"slug": "web-fetch",
		"displayName": "Web Fetch",
		"purpose": "Web fetch (allow-listed URLs only).",
		"category": "integration"
	}
] as const;
