#!/usr/bin/env bun
/**
 * generated-merge-driver — a generated file is never a merge conflict.
 *
 * WHY a conflict in a derived file is not a decision: neither side of the
 * merge is authoritative, the merged TREE is, and a generator is the
 * function from the tree to the file. So the only thing a merge owes such
 * a file is to finish without stopping; `delendai guard post-merge` then
 * runs the generators once the tree is whole and commits what moved.
 *
 * WHY the driver does not run the generator itself: git calls a driver
 * per file while the merge is still in progress, and the working tree
 * holds OURS only (measured: a driver that lists the directory does not
 * see a file THEIRS added). A generator run there computes the file from
 * half a tree, and runs once per conflicted file (dozens of `AGENT.md`).
 * That was the first version of this driver, and it produced files that
 * were neither side's nor the true one.
 *
 * What it does instead, per file:
 *   - a textual three-way merge. Two candidates that touched different
 *     rows of a table merge cleanly and the result is already right;
 *   - when that conflicts, OURS is kept and the file is left for the
 *     regeneration to correct;
 *   - for a file that is authored with a generated region inside it, the
 *     region is set aside first, the authored text is merged for real, and
 *     a conflict in that text stays a conflict, because it is somebody's
 *     decision.
 *
 * Git calls it as `%O %A %B %P`: the common ancestor, OURS (the file this
 * driver must leave correct), THEIRS, and the repository-relative path.
 */

import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { GENERATED_MERGE_RULES } from './generated-merge-driver.constant';
import type {
	IGeneratedMergeOutcome,
	IGeneratedBlock,
	IGeneratedMergeRule,
} from './generated-merge-driver.interface';

export type {
	IGeneratedMergeOutcome,
	IGeneratedBlock,
	IGeneratedMergeRule,
} from './generated-merge-driver.interface';
export { GENERATED_MERGE_RULES } from './generated-merge-driver.constant';

const matches = (candidate: string, path: string): boolean => {
	if (candidate.startsWith('/')) return path === candidate.slice(1);
	// A candidate ending in `/` is a directory: everything under it is
	// generated by the same step.
	if (candidate.endsWith('/')) {
		return path.startsWith(candidate) || path.includes(`/${candidate}`);
	}
	return path === candidate || path.endsWith(`/${candidate}`);
};

/** The rule covering a path, or undefined when the path is authored. */
export const ruleFor = (path: string): IGeneratedMergeRule | undefined =>
	GENERATED_MERGE_RULES.find((rule) =>
		rule.paths.some((candidate) => matches(candidate, path)),
	);

/** The text between the markers, markers included, or undefined. */
const regionOf = (text: string, block: IGeneratedBlock): string | undefined => {
	const from = text.indexOf(block.start);
	const to = text.indexOf(block.end);
	if (from === -1 || to === -1 || to < from) return undefined;
	return text.slice(from, to + block.end.length);
};

const setAside = (text: string, block: IGeneratedBlock): string | undefined => {
	const region = regionOf(text, block);
	return region === undefined
		? undefined
		: text.replace(region, `${block.start}\n${block.end}`);
};

/** `git merge-file`: merged text, and whether it is free of conflicts. */
export type ITextMerge = (input: {
	readonly ours: string;
	readonly base: string;
	readonly theirs: string;
}) => { readonly text: string; readonly clean: boolean };

export const gitTextMerge: ITextMerge = (input) => {
	const directory = mkdtempSync(join(tmpdir(), 'generated-merge-'));
	try {
		const files = ['ours', 'base', 'theirs'] as const;
		for (const name of files) {
			writeFileSync(join(directory, name), input[name]);
		}
		try {
			const text = execFileSync(
				'git',
				[
					'merge-file',
					'-p',
					join(directory, 'ours'),
					join(directory, 'base'),
					join(directory, 'theirs'),
				],
				{ encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] },
			);
			return { text, clean: true };
		} catch (error) {
			const status = (error as { status?: number | null }).status;
			// A positive status is the number of conflicts and stdout still
			// holds the marked-up text; anything else is a failure to merge.
			if (typeof status === 'number' && status > 0) {
				return {
					text: String((error as { stdout?: unknown }).stdout ?? ''),
					clean: false,
				};
			}
			throw error;
		}
	} finally {
		rmSync(directory, { recursive: true, force: true });
	}
};

/**
 * The merged content of one generated file.
 *
 * `content` is what the file must hold afterwards; `outcome` says how it
 * got there. An authored conflict has no content: the file is left to a
 * person.
 */
export const mergeGenerated = (input: {
	readonly rule: IGeneratedMergeRule;
	readonly base: string;
	readonly ours: string;
	readonly theirs: string;
	readonly merge?: ITextMerge;
}): { readonly outcome: IGeneratedMergeOutcome; readonly content?: string } => {
	const merge = input.merge ?? gitTextMerge;
	const { rule, base, ours, theirs } = input;
	if (rule.block === undefined) {
		const merged = merge({ ours, base, theirs });
		return merged.clean
			? { outcome: 'merged-textually', content: merged.text }
			: { outcome: 'kept-ours-for-regeneration', content: ours };
	}
	const oursRegion = regionOf(ours, rule.block);
	const apart = {
		ours: setAside(ours, rule.block),
		base: setAside(base, rule.block),
		theirs: setAside(theirs, rule.block),
	};
	if (
		oursRegion === undefined ||
		apart.ours === undefined ||
		apart.base === undefined ||
		apart.theirs === undefined
	) {
		return { outcome: 'authored-conflict' };
	}
	const merged = merge({
		ours: apart.ours,
		base: apart.base,
		theirs: apart.theirs,
	});
	if (!merged.clean) return { outcome: 'authored-conflict' };
	const placeholder = `${rule.block.start}\n${rule.block.end}`;
	return {
		outcome: 'kept-ours-for-regeneration',
		content: merged.text.replace(placeholder, () => oursRegion),
	};
};

/**
 * Resolve one file git handed over. Returns 0 when `ours` now holds the
 * resolution and 1 when the conflict must stand.
 */
export const resolveGenerated = (input: {
	readonly ours: string;
	readonly base: string;
	readonly theirs: string;
	readonly path: string;
	readonly merge?: ITextMerge;
}): number => {
	const rule = ruleFor(input.path);
	if (rule === undefined) return 1;
	try {
		const resolved = mergeGenerated({
			rule,
			base: readFileSync(input.base, 'utf8'),
			ours: readFileSync(input.ours, 'utf8'),
			theirs: readFileSync(input.theirs, 'utf8'),
			...(input.merge !== undefined ? { merge: input.merge } : {}),
		});
		if (resolved.content === undefined) return 1;
		writeFileSync(input.ours, resolved.content);
		return 0;
	} catch (error) {
		process.stderr.write(
			`generated-merge-driver: could not merge ${input.path} (${error instanceof Error ? error.message : String(error)}); the conflict stands.\n`,
		);
		return 1;
	}
};

if (import.meta.main) {
	const [base, ours, theirs, path] = process.argv.slice(2);
	if (
		base === undefined ||
		ours === undefined ||
		theirs === undefined ||
		path === undefined
	) {
		process.stderr.write(
			'generated-merge-driver: called without %O %A %B %P; nothing was resolved.\n',
		);
		process.exit(1);
	}
	process.exit(resolveGenerated({ base, ours, theirs, path }));
}
