/**
 * f00120 — wiring-doctor + monorepo-wiring writer contract.
 *
 * The six wiring points every first-party plugin in this monorepo must
 * agree on:
 *
 *   1. `tsconfig.base.json` → `compilerOptions.paths` for the plugin id.
 *   2. `vitest.shared.ts` → `workspaceAliases(...)` entries for the plugin.
 *   3. `packages/core/src/lib/plugins/plugin-defaults.ts` → `PLUGIN_DEFAULTS`
 *      entry (may be the empty object — the only invariant is that the key
 *      exists).
 *   4. `tools/scripts/release/release-plan.ts` → `PUBLISH_ORDER` entry.
 *   5. `packages/core/src/lib/plugins/preset-catalog.ts` → membership in at
 *      least one preset (usually `vertex` for host-only first-party plugins,
 *      otherwise `swarm`).
 *   6. The agent catalog — derived state, regenerated by
 *      `bun run catalog:generate`; the wiring-doctor does NOT assert it
 *      directly (it asserts that the catalog regen hook ran).
 *
 * Every writer exposed by `wire-plugin.ts` is **idempotent**: re-running on
 * a fully-wired plugin is a no-op, re-running on a half-wired plugin
 * completes the missing entries only. All writers are pure over an injected
 * `IPluginWiringFs` (no direct fs imports in the writers) so the wiring-
 * doctor can run with an in-memory fs in tests and the production writer
 * can swap to a real fs without rewiring.
 */

/** Minimal fs surface the writers + doctor need. */
export interface IPluginWiringFs {
	readonly readFile: (path: string) => Promise<string>;
	readonly writeFile: (path: string, content: string) => Promise<void>;
	readonly pathExists: (path: string) => Promise<boolean>;
}

/** A single wiring-point checker result. */
export interface IPluginWiringPoint {
	/** Stable id, e.g. `tsconfig-base`, `vitest-shared`, `plugin-defaults`. */
	readonly id: PluginWiringPointId;
	/** Absolute or repo-relative file path that was inspected. */
	readonly path: string;
	/** `true` when the point is present and well-formed. */
	readonly wired: boolean;
	/** Short, user-facing description of what was checked. */
	readonly summary: string;
	/** When `wired: false`, the smallest edit that would close the gap. */
	readonly remediation?: string;
}

export interface IPluginWiringDiagnostic {
	readonly pluginId: string;
	readonly reason: string;
	readonly fixHint: string;
}

export type PluginWiringPointId =
	| 'tsconfig-base'
	| 'vitest-shared'
	| 'plugin-defaults'
	| 'publish-order'
	| 'preset-catalog'
	| 'catalog-regen';

/** Output of the wiring-doctor: a per-point verdict + an overall verdict. */
export interface IPluginWiringReport {
	readonly pluginId: string;
	readonly points: readonly IPluginWiringPoint[];
	readonly loadDiagnostics: readonly IPluginWiringDiagnostic[];
	readonly fullyWired: boolean;
	readonly missing: readonly PluginWiringPointId[];
}

/** Inputs for every writer in `wire-plugin.ts`. */
export interface IWirePluginOptions {
	readonly pluginId: string;
	readonly fs: IPluginWiringFs;
	/**
	 * When true, the writer runs against the live repo (writes through to
	 * `tsconfig.base.json`, `vitest.shared.ts`, ...). When false, the writer
	 * computes the new contents and returns them via `IPluginWiringEdit` so a
	 * caller can preview or dry-run before applying.
	 */
	readonly dryRun?: boolean;
	/** Preset the plugin should be added to (default `vertex`). */
	readonly targetPreset?:
		| 'vertex'
		| 'full'
		| 'swarm'
		| 'standard'
		| 'minimal';
}

/** A single edit the writer wants to apply to a single file. */
export interface IPluginWiringEdit {
	readonly path: string;
	readonly previous: string;
	readonly next: string;
	/** `true` if this edit was already present (idempotent re-run). */
	readonly noop: boolean;
}

/** Output of one writer invocation. */
export interface IPluginWiringWrite {
	readonly pointId: PluginWiringPointId;
	readonly edits: readonly IPluginWiringEdit[];
	readonly wired: boolean;
}
