// Adoption analysis for an existing proposals folder (clear, human-followable).
//
// When delendai is dropped into a project that already has a proposals dir,
// the agent needs to (1) understand the canonical layout and (2) see how the
// current folder maps onto it and what to do. `analyzeProposals` is the pure
// brain: given a directory listing (+ light frontmatter), it classifies every
// entry, explains the convention, and produces an actionable plan — no I/O.

import {
	PROPOSAL_KIND_BY_PREFIX,
	PROPOSAL_KINDS,
	PROPOSAL_STATUSES,
	type IProposalKind as ICanonicalProposalKind,
} from '../contracts/constants/proposal-glossary.constant';

/** The canonical, documented layout under `<docsDir>/proposals/`. */
export const PROPOSALS_LAYOUT = {
	root: '<docsDir>/proposals  (default docs/delendai/proposals)',
	files: {
		'index.json':
			'machine-readable registry, REGENERATED by sync_proposals at <cacheDir>/proposals/index.json (default .cache/delendai/proposals/index.json) — a cache artefact, never hand-edited and never stored inside this folder',
		'README.md':
			'human guide to this folder (what each file/status bucket is)',
		'<kind><N>-<kebab-title>.md':
			'a proposal; the filename prefix is the kind (f=feat, x=fix, b=breaking, a=audit, c=chore, r=refactor, v=perf, d=docs, t=test, i=infra, s=spike, q=plan, n=resume, l=legacy); frontmatter: id, kind, status',
	},
	folders: {
		'<status>/':
			'one folder per canonical status: ready/, in-progress/, review/, done/, paused/, blocked/, retired/',
		'done/':
			'completed + verified proposals, archived out of the active set (terminal status)',
	},
} as const;

/** Re-export the glossary's canonical kind so consumers of this module stay on it. */
export type IProposalKind = ICanonicalProposalKind;

export interface IScanEntry {
	/** Entry name relative to the proposals root (e.g. `done/f00100-x.md`). */
	readonly name: string;
	readonly isDir: boolean;
	/** Light frontmatter of a `.md` file, if present. */
	readonly frontmatter?: {
		id?: string;
		status?: string;
		type?: string;
		kind?: string;
	} | null;
}

export interface IScannedProposal {
	/** Relative path from the proposals root (e.g. `done/f00100-x.md`). */
	readonly file: string;
	readonly id: string;
	readonly kind: IProposalKind;
	readonly status: string;
}

export interface IAdoptionReport {
	readonly root: string;
	readonly layout: typeof PROPOSALS_LAYOUT;
	readonly scan: {
		readonly proposals: readonly IScannedProposal[];
		readonly folders: readonly string[];
		readonly hasIndex: boolean;
		readonly hasReadme: boolean;
		/** `.md` files with no proposal frontmatter (need review/convert). */
		readonly unrecognized: readonly string[];
		/** Non-markdown, non-index files. */
		readonly other: readonly string[];
	};
	readonly plan: readonly string[];
	/** True when the folder already matches the convention (index + structure). */
	readonly ready: boolean;
}

/** Statuses that mean "finished" — canonical `done` plus foreign spellings. */
const DONE_STATES = new Set([
	'done',
	'closed',
	'completed',
	'merged',
	'shipped',
	'archived',
]);

/** The canonical status folders (one per glossary status, single source). */
const CANONICAL_FOLDERS = new Set(
	Object.values(PROPOSAL_STATUSES).map((info) => info.folder),
);

/**
 * Resolve the canonical kind: frontmatter `kind`/`type` first (when it is a
 * known kind), then the filename prefix via the glossary reverse map.
 */
const kindOf = (
	name: string,
	frontmatter: { kind?: string; type?: string } | null | undefined,
): IProposalKind => {
	for (const candidate of [frontmatter?.kind, frontmatter?.type]) {
		if (
			candidate !== undefined &&
			Object.hasOwn(PROPOSAL_KINDS, candidate)
		) {
			return candidate as IProposalKind;
		}
	}
	// The prefix lives on the BASENAME — `name` may be a nested rel path
	// (`done/f00100-x.md`), whose leading folder must not win.
	const basename = name.split('/').pop() ?? name;
	const prefix = basename.match(/^([a-z])/i)?.[1]?.toLowerCase();
	const kind =
		prefix !== undefined ? PROPOSAL_KIND_BY_PREFIX[prefix] : undefined;
	if (kind !== undefined) return kind;
	return 'feat';
};

/** Classify a directory listing against the canonical layout + build the plan. */
export const analyzeProposals = (
	root: string,
	entries: readonly IScanEntry[],
	indexPresent = false,
): IAdoptionReport => {
	const proposals: IScannedProposal[] = [];
	const folders: string[] = [];
	const unrecognized: string[] = [];
	const other: string[] = [];
	let hasReadme = false;
	// x00209: the registry index lives in the cache root (x00052), not in
	// this folder — the caller passes whether it exists.
	const hasIndex = indexPresent;

	const folderOf = (name: string): string | undefined => {
		const segments = name.split('/');
		return segments.length > 1 ? segments[0] : undefined;
	};

	for (const entry of entries) {
		if (entry.isDir) {
			folders.push(entry.name);
			continue;
		}
		const lower = entry.name.toLowerCase();
		// A top-level index.json is the pre-x00052 legacy location; the
		// canonical registry lives in the cache root. Tolerate it without
		// treating it as the canonical index.
		if (lower === 'index.json') {
			continue;
		}
		if (lower === 'readme.md') {
			hasReadme = true;
			continue;
		}
		if (lower.endsWith('.md')) {
			const fm = entry.frontmatter;
			if (fm && typeof fm.id === 'string' && fm.id.length > 0) {
				const folder = folderOf(entry.name);
				const statusFromFolder =
					folder !== undefined && CANONICAL_FOLDERS.has(folder)
						? folder
						: undefined;
				proposals.push({
					file: entry.name,
					id: fm.id,
					kind: kindOf(entry.name, fm),
					status: fm.status ?? statusFromFolder ?? 'unknown',
				});
			} else {
				unrecognized.push(entry.name);
			}
			continue;
		}
		other.push(entry.name);
	}

	const plan: string[] = [];
	if (!hasIndex) {
		plan.push(
			'Run `sync_proposals` to (re)build the registry index at <cacheDir>/proposals/index.json (a cache artefact — it does not live inside this folder).',
		);
	}
	if (!hasReadme) {
		plan.push(
			'Add a README.md describing the layout (see get_proposal_workflow for the convention).',
		);
	}
	const missingFolders = [...CANONICAL_FOLDERS].filter(
		(folder) =>
			!folders.some((existing) => existing.toLowerCase() === folder),
	);
	if (missingFolders.length > 0) {
		plan.push(
			`Create missing canonical status folder(s): ${missingFolders.join(', ')}.`,
		);
	}
	// A finished proposal still parked at the root (or in a non-terminal
	// folder) must be archived under done/.
	const doneMisplaced = proposals.filter(
		(p) =>
			DONE_STATES.has(p.status.toLowerCase()) &&
			!p.file.startsWith('done/') &&
			!p.file.startsWith('retired/'),
	);
	if (doneMisplaced.length > 0) {
		plan.push(
			`Archive ${doneMisplaced.length} finished proposal(s) into done/: ${doneMisplaced.map((p) => p.file).join(', ')}.`,
		);
	}
	if (unrecognized.length > 0) {
		plan.push(
			`Review ${unrecognized.length} markdown file(s) without proposal frontmatter (add id/kind/status, or move out): ${unrecognized.join(', ')}.`,
		);
	}
	if (proposals.length === 0 && unrecognized.length === 0) {
		plan.push(
			'Empty proposals folder — create your first with `create_proposal`.',
		);
	}

	const ready =
		hasIndex &&
		hasReadme &&
		unrecognized.length === 0 &&
		doneMisplaced.length === 0 &&
		missingFolders.length === 0;
	return {
		root,
		layout: PROPOSALS_LAYOUT,
		scan: { proposals, folders, hasIndex, hasReadme, unrecognized, other },
		plan,
		ready,
	};
};

// ---------------------------------------------------------------------------
// f00116 S1 — bootstrap actions (pure): what `apply: true` must create.
// ---------------------------------------------------------------------------

/** One idempotent bootstrap step: a file to write if it does not exist. */
export interface IBootstrapAction {
	/** Path relative to the proposals dir (POSIX). */
	readonly rel: string;
	readonly content: string;
}

/** README the bootstrap seeds — short, pointing at the live tools. */
export const BOOTSTRAP_README = [
	'# Proposals',
	'',
	'This folder is the proposals store managed by the delendai',
	'`proposals` plugin. Each proposal is one markdown file with',
	'frontmatter (`id`, `kind`, `status`, `type`, `track`) and lives in',
	'the folder matching its status:',
	'',
	'- `ready/` — executable now',
	'- `in-progress/` — someone is on it',
	'- `review/` — done, awaiting review',
	'- `done/` — completed (mirrored into per-kind subfolders)',
	'- `paused/`, `blocked/`, `retired/` — parked states',
	'',
	'Create proposals with the `create_proposal` tool (it allocates the',
	'id and validates slices), move them with `proposal_transition`, and',
	'ask `get_proposal_workflow` for the full convention. The registry',
	'index is regenerable at any time via `sync_proposals`.',
	'',
].join('\n');

/**
 * Compute the bootstrap actions for a store rooted at the proposals
 * dir: one `.gitkeep` per canonical status folder + the README. Pure —
 * the caller checks existence and writes; existing files are SKIPPED,
 * never overwritten (a hand-rolled README wins).
 */
export const buildBootstrapActions = (
	statusFolders: readonly string[],
): readonly IBootstrapAction[] => [
	...statusFolders.map((folder) => ({
		rel: `${folder}/.gitkeep`,
		content: '',
	})),
	{ rel: 'README.md', content: BOOTSTRAP_README },
];
