/**
 * The mandatory machine-disclosure every `issues-triage` comment carries.
 * GitHub comments posted by this plugin MUST start with this block so a
 * human reader always knows the response is automated.
 */
export const AUTOMATED_NOTICE = [
	'> 🤖 **Automated response** — this comment was generated by',
	'> `@delendai/issues-triage`, the internal delendai issue bot.',
	'> It performs mechanical triage; a human confirms before any fix ships.',
].join('\n');

export const withBotNotice = (body: string): string => {
	const quoted = body
		.split('\n')
		.map((line) => `> ${line}`)
		.join('\n');
	return `${AUTOMATED_NOTICE}\n>\n${quoted}`;
};
