/**
 * review-procedure.ts — the reviewer's procedure, one paragraph, served by
 * `review_queue` so every host reads the same one.
 */

/** The procedure for a server whose tools are prefixed with `prefix`. */
export const procedureFor = (prefix: string): string =>
	'Reviewers work as a swarm, each in ONE review batch: a single work branch that carries every proposal you review this round and becomes ONE pull request. Enter it once (the `claim` field shows how), then for each proposal with no `claimedBy`: claim it with its `claim` commit BEFORE reading it, review it in the batch worktree — pass that worktree as `checkout` on every ' +
	`${prefix}_proposal_review and ${prefix}_proposal_transition call — and commit there after EACH verdict, so the progress shows on the branch while you go. When the batch is done, \`delendai work publish\` it once. Never open a pull request per proposal, never open one from the work branch itself, never name the branch or pick an author by hand: the tools name the ref (agent = your model id, kind = review) and git authors the commits as the repository's identity. Change a proposal's state only with ${prefix}_proposal_transition, which moves the file and updates the database together; editing its status by hand does neither. If another agent already claimed a proposal, take the next one. Never review a proposal another agent holds. ` +
	'The queue lists each slice\u2019s state; call it again with `proposalId` for the proposal you have claimed, to get its delivering commits, files, acceptance and later changes. For each slice marked needs-verdict: read the diff of the delivering commit, run its gate, and check every acceptance item and the proposal non-goals against what that commit delivered; look for regressions and out-of-scope changes. ' +
	'A slice is judged on what it delivered, not on today’s code: if the code differs now and `changedSince` names a later commit that changed it (another proposal superseding, extending or reverting it), that is not a defect of this slice — approve on the delivered state and name those commits in the note. When `changedSinceTruncated` is set, the list is only the newest of them: read the rest with `git log` on the slice files before judging. Request changes only for what the delivery itself got wrong. ' +
	`Record the verdict with ${prefix}_proposal_review only — approve with evidence, or request_changes with a note that says what is wrong, where, how to reproduce it and what must hold to approve. ` +
	'A delivery nobody signed is reviewed as unrecorded: independence cannot be verified, so say exactly what you checked. Never edit code, never submit on the implementer’s behalf, never move a proposal by hand. A blocked slice is reported with its missing datum and skipped; a proposal whose slices are all approved is closed with the call in its `close` field. ' +
	'Work oldest first and do not stop at the first finding: every proposal in review gets a verdict or a stated blocker.';
