/**
 * review-procedure.ts — the reviewer's procedure, one paragraph, served by
 * `review_queue` so every host reads the same one.
 */

import { REVIEW_PACK_SIZE } from '../contracts/constants/review-claims.constant';

/** The procedure for a server whose tools are prefixed with `prefix`. */
export const procedureFor = (prefix: string): string =>
	`Review in packs of ${String(REVIEW_PACK_SIZE)} proposals: one review unit per pack, one pull request per pack. From a terminal in this repository, \`delendai review next --agent=<your model id>\` enters your review unit (pass the \`--session\` it prints on later calls, or run them from inside your unit's worktree), claims the next proposal nobody holds, and lists each slice to judge with the exact approve and changes commands. ` +
	'For each slice: read the diff of its delivering commit, run its gate, and check every acceptance item and the proposal non-goals against what that commit delivered; look for regressions and out-of-scope changes. ' +
	'A slice is judged on what it delivered, not on today\u2019s code: if the code differs now and `changedSince` names a later commit that changed it (another proposal superseding, extending or reverting it), that is not a defect of this slice \u2014 approve on the delivered state and name those commits in the note. When `changedSinceTruncated` is set, the list is only the newest of them: read the rest with `git log` on the slice files before judging. Request changes only for what the delivery itself got wrong. ' +
	'Answer with `delendai review approve` (the gate\u2019s exit code and test counts are its evidence) or `delendai review changes` with a note that says what is wrong, where, how to reproduce it and what must hold to approve. Each verdict is committed to your unit as it is recorded; the last approval closes the proposal and a change request reopens it. Then `delendai review next` again: once your pack is full it publishes the pack as its pull request and continues in a new unit, and when nothing is left it publishes what you judged. Never open a second unit to keep claiming, and never leave a unit unpublished. ' +
	`Without a terminal the steps are the same, through MCP: enter with the \`work\` tool \`{ action: "enter", kind: "review", proposal: "batch", slice: "all", agent }\`, claim it with ${prefix}_review_claim, call this queue with \`unit\` (your unit\u2019s work ref) so only your claims count as yours, and again with \`proposalId\` for its evidence, record each verdict with ${prefix}_proposal_review, passing your unit\u2019s worktree as \`checkout\` to both, and when the queue's \`pack.full\` is true (the claim is refused then too), publish with the \`work\` tool \`{ action: "publish", kind: "review", proposal: "batch", slice: "all", agent }\` and enter again for the next pack. ` +
	'A delivery nobody signed is reviewed as unrecorded: independence cannot be verified, so say exactly what you checked. Never edit code (a review unit that changes anything but documents is refused at commit and at publish), never submit on the implementer\u2019s behalf, never move a proposal by hand or with git, never delete or rename a branch, never review a proposal another agent holds, never apply the owner\u2019s `delendai:owner-reconcile` label: carrying other reviewers\u2019 verdicts in a `reconcile` unit is the owner\u2019s call. A blocked slice is reported with its missing datum and skipped. ' +
	'Work oldest first and do not stop at the first finding: every proposal in review gets a verdict or a stated blocker.';
