import fc from 'fast-check';
import { describe, expect, it } from 'vitest';

import { reconcileProposalMarkdown } from '../../src/lib/reconciler-markdown';

type TOperation =
	| { readonly kind: 'create'; readonly id: number }
	| { readonly kind: 'update'; readonly id: number }
	| { readonly kind: 'transition'; readonly id: number }
	| { readonly kind: 'delete'; readonly id: number };

const operationArbitrary: fc.Arbitrary<TOperation> = fc
	.record({
		kind: fc.constantFrom('create', 'update', 'transition', 'delete'),
		id: fc.integer({ min: 0, max: 24 }),
	})
	.map(({ kind, id }) => ({ kind, id }) as TOperation);

const markdownFor = (id: number, title: string, status: string): string => `---
id: x${String(id).padStart(5, '0')}
title: ${title}
kind: fix
status: ${status}
type: proposal
track: property-test
---
# ${title}

Generated by the digest property test.
`;

const filesFor = (operations: readonly TOperation[]) => {
	const state = new Map<number, { title: string; status: string }>();

	for (const operation of operations) {
		const current = state.get(operation.id);
		switch (operation.kind) {
			case 'create':
				state.set(operation.id, {
					title: `Proposal ${operation.id}`,
					status: 'ready',
				});
				break;
			case 'update':
				if (current !== undefined) {
					state.set(operation.id, {
						...current,
						title: `${current.title} updated`,
					});
				}
				break;
			case 'transition':
				if (current !== undefined) {
					state.set(operation.id, {
						...current,
						status:
							current.status === 'ready' ? 'in-progress' : 'done',
					});
				}
				break;
			case 'delete':
				state.delete(operation.id);
				break;
		}
	}

	return [...state.entries()].map(([id, value]) => ({
		path: `ready/fixes/x${String(id).padStart(5, '0')}.md`,
		raw: markdownFor(id, value.title, value.status),
	}));
};

describe('proposal digest property (a00094 S2)', () => {
	it('preserves the digest across generated CRUD sequences and rebuild order', () => {
		fc.assert(
			fc.property(
				fc.array(operationArbitrary, { minLength: 1, maxLength: 40 }),
				fc.integer(),
				(operations, shuffleSeed) => {
					const files = filesFor(operations);
					const before = reconcileProposalMarkdown({
						mode: 'shadow',
						sourceCommit: 'property-test',
						files,
					});
					const shuffled = [...files].sort(
						(left, right) =>
							((left.path.length + shuffleSeed) % 17) -
							((right.path.length + shuffleSeed) % 17)
					);
					const after = reconcileProposalMarkdown({
						mode: 'shadow',
						sourceCommit: 'property-test',
						files: shuffled,
					});

					expect(after.logicalDigest).toBe(before.logicalDigest);
					expect(after.proposals).toEqual(before.proposals);
				}
			),
			{ numRuns: 50 }
		);
	});
});
