import { definePluginManifest, TOKEN_BUDGETS } from '@mcp-vertex/core/public';

export default definePluginManifest({
	id: 'audit-orchestrator',
	package: '@mcp-vertex/audit-orchestrator',
	version: '0.1.0',
	visibility: 'public',
	summary:
		'Orchestrates implementation work generated by project-agnostic audit plan proposals.',
	tags: ['audit', 'orchestrator', 'subagent', 'proposals'],
	maturity: 'experimental',
	permissions: ['filesystem-read', 'process'],
	presets: [],
	tokenBudget: TOKEN_BUDGETS.toolPayloads.search,
	dependencies: ['@mcp-vertex/core', '@mcp-vertex/agent-orchestrator', 'zod'],
	capabilities: ['audit-orchestration', 'subagent-dispatch'],
});
