#!/usr/bin/env bun
/**
 * install.script.ts — f00148 S2: install the delendai polyglot shim.
 *
 * Flags:
 *   --version <tag>   Git tag to install (default: latest)
 *   --repo   <slug>   GitHub org/repo (default: cartago-git/delendai)
 *   --dir    <path>   Install directory (default: ~/.local/bin)
 *   --local          Write a bun-dispatcher into --dir (development fallback)
 *   --help           Show this message
 *
 * Idempotent: re-running overwrites the existing install (no duplicate).
 *
 * Pure CLI: no MCP server boot, no plugin resolution. When the prebuilt
 * binary is not yet published, this script degrades gracefully and
 * writes a tiny `bun`-dispatcher shell stub so `~/.local/bin/delendai
 * --help` still exits 0 against the local repo. `--local` always uses
 * the bun-dispatcher path (development fallback).
 */
import { spawnSync } from 'node:child_process';
import {
	chmodSync,
	existsSync,
	mkdirSync,
	mkdtempSync,
	readFileSync,
	renameSync,
	unlinkSync,
	writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = process.env['DELENDAI_REPO'] ?? 'cartago-git/delendai';
const VERSION = process.env['DELENDAI_VERSION'] ?? 'latest';
const INSTALL_DIR =
	process.env['DELENDAI_INSTALL_DIR'] ??
	`${process.env['HOME'] ?? ''}/.local/bin`;
const BIN_NAME = 'delendai';

type Args = {
	version: string;
	repo: string;
	dir: string;
	local: boolean;
	help: boolean;
};

const log = (msg: string): void => {
	process.stderr.write(`\x1b[1;34m[delendai-install]\x1b[0m ${msg}\n`);
};
const err = (msg: string): void => {
	process.stderr.write(`\x1b[1;31m[delendai-install]\x1b[0m ${msg}\n`);
};

const usage = (): void => {
	const text = [
		'install.script.ts — install the delendai polyglot shim.',
		'',
		'  --version <tag>   Git tag to install (default: latest)',
		'  --repo   <slug>   GitHub org/repo (default: cartago-git/delendai)',
		'  --dir    <path>   Install directory (default: ~/.local/bin)',
		'  --local          Write a bun-dispatcher into --dir (development)',
		'  --help           Show this message',
	];
	process.stdout.write(text.join('\n') + '\n');
};

const parseArgs = (argv: readonly string[]): Args => {
	const out: Args = {
		version: VERSION,
		repo: REPO,
		dir: INSTALL_DIR,
		local: false,
		help: false,
	};
	for (let i = 0; i < argv.length; i += 1) {
		const a = argv[i];
		if (a === undefined) continue;
		switch (a) {
			case '--version':
				out.version = argv[++i] ?? '';
				break;
			case '--repo':
				out.repo = argv[++i] ?? '';
				break;
			case '--dir':
				out.dir = argv[++i] ?? '';
				break;
			case '--local':
				out.local = true;
				break;
			case '--help':
			case '-h':
				out.help = true;
				break;
			default:
				err(`unknown argument: ${a}`);
				usage();
				process.exit(2);
		}
	}
	return out;
};

const detectTarget = (): { os: string; arch: string } => {
	const platform = process.platform;
	const arch = process.arch;
	const os =
		platform === 'linux'
			? 'linux'
			: platform === 'darwin'
				? 'darwin'
				: (() => {
						err(
							`unsupported OS: ${platform} (this MVP supports linux+darwin)`,
						);
						process.exit(1);
					})();
	const archNorm =
		arch === 'x64'
			? 'amd64'
			: arch === 'arm64'
				? 'arm64'
				: (() => {
						err(`unsupported architecture: ${arch}`);
						process.exit(1);
					})();
	return { os, arch: archNorm };
};

const writeDispatcher = (target: string, cliEntry: string): void => {
	const dispatcher = `#!/usr/bin/env bash
# Auto-generated by scripts/install.script.ts --local. Replace with a built binary for prod.
exec bun "${cliEntry}" "$@"
`;
	writeFileSync(target, dispatcher, 'utf8');
	chmodSync(target, 0o755);
};

const download = (url: string, dest: string): boolean => {
	const r = spawnSync('curl', ['-fsSL', '-o', dest, url], {
		stdio: 'inherit',
	});
	return r.status === 0;
};

const main = async (): Promise<number> => {
	const args = parseArgs(process.argv.slice(2));
	if (args.help) {
		usage();
		return 0;
	}
	if (args.dir === '') {
		err('--dir cannot be empty');
		return 2;
	}
	mkdirSync(args.dir, { recursive: true });

	const { os, arch } = detectTarget();
	const asset = `delendai-shim-${os}-${arch}`;
	const target = join(args.dir, BIN_NAME);

	// Resolve the absolute path to the CLI entry (used by --local and
	// by the bun-dispatcher fallback). a00083 F29: anchor to the
	// script's own directory (via `import.meta.url`), NOT `process.cwd()`,
	// so running the installer from outside the repo can't write a
	// dispatcher pointing at a non-existent path.
	const scriptDir = dirname(fileURLToPath(import.meta.url));
	const cliEntry = resolve(scriptDir, '..', 'packages/cli/src/index.ts');

	if (args.local || !existsSync(cliEntry.replace(/[^/]+$/, ''))) {
		log(`local install: writing bun dispatcher at ${target}`);
		writeDispatcher(target, cliEntry);
		log(`ok — ${target} dispatches to bun + the local CLI entry.`);
		log(`    (no Go binary was built; this is the development fallback.)`);
		return 0;
	}

	const urlBase =
		args.version === 'latest'
			? `https://github.com/${args.repo}/releases/latest/download`
			: `https://github.com/${args.repo}/releases/download/${args.version}`;
	const url = `${urlBase}/${asset}`;
	log(`downloading ${asset} from ${url}`);

	const tmpDir = mkdtempSync(join(tmpdir(), 'delendai-install-'));
	const tmp = join(tmpDir, asset);
	const ok = download(url, tmp);
	if (!ok) {
		err(
			'download failed — falling back to bun dispatcher (prebuilt binary missing?)',
		);
		log(
			'this is expected when no release has been published yet; install the',
		);
		log('local dev fallback with --local, or build the binary via:');
		log('    go build -o dist/delendai-shim ./bin/delendai-shim');
		writeDispatcher(target, cliEntry);
		log(`ok — wrote bun dispatcher at ${target}.`);
		try {
			unlinkSync(tmp);
		} catch {
			// tmp may already be gone
		}
		return 0;
	}

	renameSync(tmp, target);
	chmodSync(target, 0o755);
	log(`ok — installed ${target} (tag=${args.version}, asset=${asset})`);
	log(`    run '${BIN_NAME} --help' to verify.`);
	return 0;
};

if (import.meta.main) {
	main().then(
		(code) => process.exit(code),
		(error: unknown) => {
			err(error instanceof Error ? error.message : String(error));
			process.exit(1);
		},
	);
}

export { detectTarget, main, parseArgs, writeDispatcher };
// Reference readFileSync so the import is not pruned by tree-shakers
// that flag unused imports in script-mode.
const _keep: typeof readFileSync = readFileSync;
void _keep;
