import type { IPluginRegistryEntry } from '@mcp-vertex/core/public';

import { describe, expect, it } from 'vitest';

import type { IPluginCatalogEntry } from './generate-catalog.script.ts';
import {
	buildCatalogEntries,
	renderCatalogMarkdown,
	renderReadmePluginTable,
} from './generate-catalog.script.ts';

describe('generate-catalog', () => {
	it('prefers migrated manifest summaries while keeping index-only plugins', () => {
		const entries: readonly IPluginRegistryEntry[] = [
			{
				origin: 'first-party',
				id: 'search',
				package: '@mcp-vertex/search',
				summary: 'Index summary.',
				tags: ['search'],
				permissions: ['filesystem-read'],
			},
			{
				origin: 'first-party',
				id: 'custom',
				package: '@mcp-vertex/custom',
				summary: 'Index-only summary.',
				tags: ['custom'],
				permissions: ['filesystem-read'],
			},
			{
				origin: 'first-party',
				id: 'search',
				package: '@mcp-vertex/search',
				summary: 'Generated manifest summary.',
				tags: ['search', 'generated'],
				permissions: ['filesystem-read'],
			},
		];
		const packages = [
			{
				id: 'search',
				dir: 'plugins/search',
				manifestPath: 'plugins/search/plugin.manifest.ts',
				packagePath: 'plugins/search/package.json',
				packageName: '@mcp-vertex/search',
				version: '1.2.3',
				private: false,
			},
			{
				id: 'custom',
				dir: 'plugins/custom',
				manifestPath: 'plugins/custom/plugin.manifest.ts',
				packagePath: 'plugins/custom/package.json',
				packageName: '@mcp-vertex/custom',
				version: '0.2.0',
				private: false,
			},
		] as const;
		const migratedManifests = [
			{
				...packages[0],
				manifest: {
					id: 'search',
					package: '@mcp-vertex/search',
					version: '1.2.3',
					visibility: 'public',
					summary: 'Manifest summary wins.',
					tags: ['search', 'manifest'],
					maturity: 'stable',
					permissions: ['filesystem-read'],
					presets: ['minimal'],
					tokenBudget: {
						warning: 1,
						hard: 2,
						releaseRelativePercent: 3,
					},
					dependencies: ['@mcp-vertex/core'],
					capabilities: ['lexical-search'],
				},
			},
		] as const;

		const catalog = buildCatalogEntries(
			entries,
			packages,
			migratedManifests,
		);
		expect(catalog).toHaveLength(2);
		expect(catalog[1]).toMatchObject({
			id: 'search',
			summary: 'Manifest summary wins.',
			summarySource: 'manifest',
			capabilities: ['lexical-search'],
			capabilitySource: 'manifest',
		});
		expect(catalog[0]).toMatchObject({
			id: 'custom',
			summary: 'Index-only summary.',
			summarySource: 'index',
			capabilities: [],
			capabilitySource: 'index-only',
		});
	});

	it('renders the README table and generated docs from catalog entries', () => {
		const entries: readonly IPluginCatalogEntry[] = [
			{
				id: 'custom',
				path: 'plugins/custom',
				package: '@mcp-vertex/custom',
				version: '0.2.0',
				summary: 'Index-only summary.',
				summarySource: 'index',
				defaultPreset: 'none',
				presetMembership: [],
				capabilities: [],
				capabilitySource: 'index-only',
				permissions: ['filesystem-read'],
				tags: ['custom'],
			},
		];
		expect(renderReadmePluginTable(entries)).toContain(
			'| `plugins/custom` | `@mcp-vertex/custom` | Index-only summary. |',
		);
		const markdown = renderCatalogMarkdown(entries);
		expect(markdown).toContain(
			'<!-- Auto-generated by bun tools/scripts/docs/generate-catalog.script.ts -->',
		);
		expect(markdown).toContain('## Versions');
		expect(markdown).toContain('not declared (index-only)');
	});
});
