interface IErrorReportingKnowledgeOptions {
	readonly prefix: string;
	readonly targetRepo: string;
}

export function buildErrorReportingKnowledge(
	options: IErrorReportingKnowledgeOptions,
): string {
	return [
		'# Automatic mcp-vertex error reporting',
		'',
		'`@mcp-vertex/error-reporting` detects failures that originate inside',
		'mcp-vertex itself (not the host project) and opens a de-duplicated,',
		'safe issue on one fixed allowlisted GitHub repository using only',
		'MCP Vertex-owned metadata.',
		'',
		'## Behaviour',
		'',
		'- Disabled by default; network dispatch is **explicit opt-in** via',
		'  `plugins.error-reporting.options.enabled = true`.',
		'- External project data is **non-reportable by construction**. The',
		'  reporter accepts only mcp-vertex-internal failures backed by typed',
		'  internal errors or `@mcp-vertex/*` frame evidence.',
		'- De-duplicated by a stable fingerprint built from safe internal data.',
		'- Raw message, stack, args, result, cwd and repo/workspace data are not',
		'  part of the public report contract.',
		'- Dispatch uses `gh issue create` through the shared CLI runner. The',
		'  plugin passes only `argv` and `cwd`; it does **not** forward project',
		'  headers or environment variables.',
		'- Never blocks or breaks the server: without `gh` or authentication the',
		'  report is recorded locally; without network the plugin stops before',
		'  invoking `gh issue create`.',
		'',
		'## Fixed destination',
		'',
		`- Current allowlisted target: \`${options.targetRepo}\`.`,
		'- The destination is fixed by MCP Vertex. Project configuration cannot',
		'  redirect it, and runtime/project data is never consulted.',
		'- This privacy boundary is not configurable; there is no runtime flag to',
		'  re-enable reporting of external project data.',
		'',
		'## Exact transmitted fields',
		'',
		'- Safe DTO fields: `reporterVersion`, `mcpVertexVersion`, `packageId`,',
		'  `safeToolId`, `toolOwner`, `toolCategory`, `errorCode`,',
		'  `failureClass`, `classification`,',
		'  `fingerprint`, `mcpFrames`, `syntheticExample`, `environmentClass`.',
		'- `mcpVertexVersion` comes from the published `@mcp-vertex/core` package',
		'  version, never from the monorepo root `package.json`.',
		'- Issue-body table fields: `packageId`, `reporterVersion`,',
		'  `mcpVertexVersion`, `classification`, `failureClass`, `fingerprint`,',
		'  `safeToolId`, `toolOwner`, `toolCategory`, `errorCode`,',
		'  `environmentClass`.',
		'- Issue-body sections: `mcpFrames`, `syntheticExample`, the serialized',
		'  safe payload JSON, and disable instructions.',
		'- Never sent: message, stack, args, result, workspace, cwd, paths, repo',
		'  names from the host, branches, files, prompts, URLs, env, headers.',
		'',
		'## Enable it',
		'',
		'```jsonc',
		'{ "plugins": { "error-reporting": { "options": { "enabled": true } } } }',
		'```',
		'',
		`Inspect state with the \`${options.prefix}_report_status\` tool.`,
		'',
		'## Legal checklist',
		'',
		'- Review the privacy policy / notice shown to operators before enabling',
		'  third-party reporting.',
		'- Review the relevant legal bases for processing in the target markets.',
		'- Confirm the transmitted data cannot include user/project IP or IP-owned',
		'  material beyond the fixed GitHub transport metadata added by the',
		'  connection itself.',
		'- Review issue retention and public visibility on the target GitHub repo.',
		'- Review GitHub / gh CLI metadata that may exist outside the issue body',
		'  itself (network/IP/account-level metadata).',
		'- Confirm that no user/project context is collected or transmitted by the',
		'  plugin design.',
		'',
		'This knowledge entry is operational guidance only and is **not legal',
		'advice**.',
	].join('\n');
}
