// i18n catalogue for `delendai_orchestrator-runner_advise_spend`.
//
// Per-tool i18n entry (apps/web/src/i18n/tools/orchestrator-runner/). The
// 12-lang invariant is enforced by `check-i18n.ts` once the entry opts in
// via `apps/web/src/i18n/tools/index.ts` (S9 wiring).

import type { IToolI18n } from '#I18N/tools/_shape';

export const orchestratorRunnerAdviseSpendI18n: IToolI18n = {
	description: {
		en: "Act as a cost analyst over recorded usage. Reads spend grouped by provider, plugin, agent and extension plus the circuit-breaker limitsStatus (rolling session + monthly spend against your caps) and returns observations plus risk-graded (low/medium/high) recommendations — e.g. 'you have $12 of your $50 monthly cap left; consider switching to a cheaper model for the rest of the week.' Non-destructive: it never edits your config or roster; you confirm any change yourself.",
		es: 'Actúa como analista de costes sobre el uso registrado. Lee el gasto agrupado por proveedor, plugin, agente y extensión, más el limitsStatus del cortacircuitos (gasto continuo de sesión + mensual frente a tus límites) y devuelve observaciones más recomendaciones graduadas por riesgo (bajo/medio/alto) — p. ej. «te quedan 12 $ de tu límite mensual de 50 $; considera cambiar a un modelo más barato durante el resto de la semana». No destructivo: nunca edita tu configuración ni tu lista; tú confirmas cualquier cambio.',
		fr: "Agit comme analyste des coûts sur l'usage enregistré. Lit les dépenses regroupées par fournisseur, plugin, agent et extension, plus le limitsStatus du coupe-circuit (dépense glissante de session + mensuelle par rapport à vos plafonds) et renvoie des observations ainsi que des recommandations graduées par risque (faible/moyen/élevé) — p. ex. « il vous reste 12 $ sur votre plafond mensuel de 50 $ ; envisagez un modèle moins cher pour le reste de la semaine. » Non destructif : il ne modifie jamais votre configuration ni votre liste ; vous confirmez tout changement vous-même.",
		de: 'Agiert als Kostenanalyst über die aufgezeichnete Nutzung. Liest die nach Anbieter, Plugin, Agent und Erweiterung gruppierten Ausgaben plus den limitsStatus des Schutzschalters (fortlaufende Sitzungs- + Monatsausgaben gegen deine Obergrenzen) und liefert Beobachtungen sowie risikoabgestufte (niedrig/mittel/hoch) Empfehlungen — z. B. „Dir bleiben 12 $ von deinem 50-$-Monatslimit; erwäge, für den Rest der Woche auf ein günstigeres Modell zu wechseln.“ Nicht destruktiv: Es bearbeitet nie deine Konfiguration oder Liste; jede Änderung bestätigst du selbst.',
		it: "Agisce come analista dei costi sull'uso registrato. Legge la spesa raggruppata per provider, plugin, agente ed estensione più il limitsStatus dell'interruttore (spesa progressiva di sessione + mensile rispetto ai tuoi limiti) e restituisce osservazioni più raccomandazioni graduate per rischio (basso/medio/alto) — ad es. «ti restano 12 $ del tuo limite mensile di 50 $; valuta di passare a un modello più economico per il resto della settimana». Non distruttivo: non modifica mai la tua configurazione o il tuo elenco; sei tu a confermare ogni modifica.",
		pt: 'Atua como analista de custos sobre o uso registado. Lê os gastos agrupados por fornecedor, plugin, agente e extensão, além do limitsStatus do disjuntor (gasto contínuo de sessão + mensal face aos teus limites) e devolve observações mais recomendações graduadas por risco (baixo/médio/alto) — p. ex. «restam-te 12 $ do teu limite mensal de 50 $; considera mudar para um modelo mais barato no resto da semana». Não destrutivo: nunca edita a tua configuração nem a tua lista; és tu que confirmas qualquer alteração.',
		ja: '記録された使用状況に対してコストアナリストとして機能します。プロバイダー・プラグイン・エージェント・拡張ごとにグループ化した支出に加え、サーキットブレーカーの limitsStatus(上限に対する累積セッション支出+月間支出)を読み取り、観察結果とリスク別(低/中/高)の推奨事項を返します。例:「月間上限50ドルのうち残り12ドルです。今週の残りはより安価なモデルへの切り替えを検討してください。」非破壊的で、設定やロスターを編集することはありません。変更はすべてあなた自身が確認します。',
		zh: '作为成本分析师分析已记录的用量。读取按提供方、插件、代理和扩展分组的支出,以及断路器的 limitsStatus(相对于上限的滚动会话支出与月度支出),并返回观察结果以及按风险分级(低/中/高)的建议——例如「你 50 美元月度上限还剩 12 美元;本周剩余时间可考虑切换到更便宜的模型。」非破坏性:它从不修改你的配置或名单;任何更改都由你自己确认。',
		hi: 'रिकॉर्ड किए गए उपयोग पर लागत विश्लेषक की तरह काम करता है। प्रदाता, प्लगइन, एजेंट और एक्सटेंशन के अनुसार समूहित खर्च के साथ-साथ सर्किट-ब्रेकर का limitsStatus (आपकी सीमाओं के मुकाबले चालू सत्र + मासिक खर्च) पढ़ता है और अवलोकन तथा जोखिम-श्रेणीबद्ध (कम/मध्यम/उच्च) अनुशंसाएँ लौटाता है — जैसे «आपकी $50 मासिक सीमा में से $12 शेष हैं; बाकी सप्ताह के लिए सस्ते मॉडल पर स्विच करने पर विचार करें।» गैर-विनाशकारी: यह कभी आपका कॉन्फ़िगरेशन या सूची संपादित नहीं करता; किसी भी बदलाव की पुष्टि आप स्वयं करते हैं।',
		ar: 'يعمل كمحلل تكلفة على الاستخدام المُسجَّل. يقرأ الإنفاق مُجمَّعًا حسب المزوّد والإضافة والوكيل والامتداد إضافةً إلى limitsStatus الخاص بقاطع الدائرة (إنفاق الجلسة المتجدد + الشهري مقابل حدودك)، ويعيد ملاحظات وتوصيات مُصنَّفة حسب الخطورة (منخفض/متوسط/مرتفع) — مثل «تبقّى لديك 12 دولارًا من حدّك الشهري البالغ 50 دولارًا؛ فكّر في التحوّل إلى نموذج أرخص لبقية الأسبوع.» غير مُدمِّر: لا يعدّل أبدًا إعداداتك أو قائمتك؛ أنت من يؤكّد أي تغيير.',
		th: 'ทำหน้าที่เป็นนักวิเคราะห์ต้นทุนบนการใช้งานที่บันทึกไว้ อ่านค่าใช้จ่ายที่จัดกลุ่มตามผู้ให้บริการ ปลั๊กอิน เอเจนต์ และส่วนขยาย พร้อมกับ limitsStatus ของเบรกเกอร์ (ยอดใช้จ่ายสะสมของเซสชัน + รายเดือนเทียบกับเพดานของคุณ) แล้วคืนค่าข้อสังเกตพร้อมคำแนะนำที่จัดระดับความเสี่ยง (ต่ำ/กลาง/สูง) — เช่น «คุณเหลือ $12 จากเพดานรายเดือน $50 ลองพิจารณาเปลี่ยนไปใช้โมเดลที่ถูกกว่าในช่วงที่เหลือของสัปดาห์» ไม่ทำลายข้อมูล: มันไม่แก้ไขการตั้งค่าหรือรายชื่อของคุณเลย คุณเป็นผู้ยืนยันการเปลี่ยนแปลงใด ๆ เอง',
		vi: 'Đóng vai trò nhà phân tích chi phí trên mức sử dụng đã ghi. Đọc chi tiêu được nhóm theo nhà cung cấp, plugin, tác nhân và tiện ích mở rộng cùng limitsStatus của bộ ngắt mạch (chi tiêu phiên lũy tiến + hằng tháng so với hạn mức của bạn) và trả về các quan sát cùng khuyến nghị phân loại theo rủi ro (thấp/trung bình/cao) — ví dụ «bạn còn 12 $ trong hạn mức hằng tháng 50 $; hãy cân nhắc chuyển sang mô hình rẻ hơn cho phần còn lại của tuần.» Không phá hủy: nó không bao giờ chỉnh sửa cấu hình hay danh sách của bạn; bạn tự xác nhận mọi thay đổi.',
	},
};
