// i18n catalogue for `delendai_orchestrator-runner_bootstrap_providers`.
//
// Per-tool i18n entry. The 12-lang invariant is enforced by `check-i18n.ts`
// once the entry opts in via `apps/web/src/i18n/tools/index.ts` (S9 wiring).

import type { IToolI18n } from '#I18N/tools/_shape';

export const orchestratorRunnerBootstrapProvidersI18n: IToolI18n = {
	description: {
		en: 'Run the provider bootstrap wizard. Probes the PATH for provider CLIs, runs a best-effort auth/status RPC per detected tool to learn its tier, writes a draft roster to the cache (roster.draft.json), and returns {detected, missing, rosterDraftPath, configPatch, brief, note}. The brief is prose the assistant relays to the user (asking spend preference + task types). configPatch is an RFC 6902 JSON Patch that adds the newly-discovered providers to delendai.config.json#providers — apply it via elicitation / a CLI prompt only after the user confirms. The wizard never writes the confirmed config itself. Spawns subprocesses and writes the cache draft; never spends on a model.',
		es: 'Ejecuta el asistente de arranque de proveedores. Sondea el PATH en busca de CLI de proveedores, ejecuta un RPC de auth/estado de mejor esfuerzo por herramienta detectada para conocer su nivel, escribe un borrador de lista en la caché (roster.draft.json) y devuelve {detected, missing, rosterDraftPath, configPatch, brief, note}. El brief es prosa que el asistente transmite al usuario (preguntando preferencia de gasto y tipos de tarea). configPatch es un JSON Patch RFC 6902 que añade los proveedores recién descubiertos a delendai.config.json#providers: aplícalo mediante elicitación o un prompt de CLI solo tras la confirmación del usuario. El asistente nunca escribe la configuración confirmada. Lanza subprocesos y escribe el borrador en caché; nunca gasta en un modelo.',
		fr: "Lance l'assistant d'initialisation des fournisseurs. Sonde le PATH pour les CLI de fournisseurs, exécute un RPC auth/statut au mieux par outil détecté pour connaître son niveau, écrit un brouillon de liste dans le cache (roster.draft.json) et renvoie {detected, missing, rosterDraftPath, configPatch, brief, note}. Le brief est un texte que l'assistant transmet à l'utilisateur (demandant la préférence de dépense et les types de tâches). configPatch est un JSON Patch RFC 6902 qui ajoute les fournisseurs nouvellement détectés à delendai.config.json#providers — appliquez-le via élicitation ou une invite CLI seulement après confirmation de l'utilisateur. L'assistant n'écrit jamais la configuration confirmée lui-même. Lance des sous-processus et écrit le brouillon en cache ; ne dépense jamais pour un modèle.",
		de: 'Führt den Provider-Bootstrap-Assistenten aus. Prüft den PATH auf Provider-CLIs, führt pro erkanntem Tool einen Best-Effort-Auth-/Status-RPC aus, um seine Stufe zu ermitteln, schreibt einen Entwurf der Liste in den Cache (roster.draft.json) und gibt {detected, missing, rosterDraftPath, configPatch, brief, note} zurück. Das brief ist Prosa, die der Assistent an den Benutzer weitergibt (fragt nach Ausgabepräferenz und Aufgabentypen). configPatch ist ein RFC-6902-JSON-Patch, der die neu entdeckten Provider zu delendai.config.json#providers hinzufügt — wende ihn per Elicitation / einer CLI-Eingabeaufforderung erst nach Bestätigung des Benutzers an. Der Assistent schreibt die bestätigte Konfiguration nie selbst. Startet Subprozesse und schreibt den Cache-Entwurf; gibt nie Geld für ein Modell aus.',
		it: "Esegue la procedura guidata di bootstrap dei provider. Sonda il PATH per le CLI dei provider, esegue un RPC auth/stato best-effort per ogni strumento rilevato per conoscerne il livello, scrive una bozza di elenco nella cache (roster.draft.json) e restituisce {detected, missing, rosterDraftPath, configPatch, brief, note}. Il brief è prosa che l'assistente riferisce all'utente (chiedendo preferenza di spesa e tipi di attività). configPatch è un JSON Patch RFC 6902 che aggiunge i provider appena scoperti a delendai.config.json#providers — applicalo tramite elicitation / un prompt CLI solo dopo la conferma dell'utente. La procedura non scrive mai la configurazione confermata. Avvia sottoprocessi e scrive la bozza in cache; non spende mai per un modello.",
		pt: 'Executa o assistente de arranque de fornecedores. Sonda o PATH por CLIs de fornecedores, executa um RPC de auth/estado de melhor esforço por ferramenta detetada para saber o seu nível, escreve um rascunho de lista na cache (roster.draft.json) e devolve {detected, missing, rosterDraftPath, configPatch, brief, note}. O brief é prosa que o assistente transmite ao utilizador (perguntando preferência de gasto e tipos de tarefa). configPatch é um JSON Patch RFC 6902 que adiciona os fornecedores recém-descobertos a delendai.config.json#providers — aplique-o via elicitação / um prompt de CLI apenas após a confirmação do utilizador. O assistente nunca escreve a configuração confirmada. Lança subprocessos e escreve o rascunho em cache; nunca gasta num modelo.',
		ja: 'プロバイダーのブートストラップウィザードを実行します。PATH でプロバイダー CLI を探し、検出した各ツールに対してベストエフォートの auth/status RPC を実行してそのティアを取得し、ドラフトのロスターをキャッシュ(roster.draft.json)に書き込み、{detected, missing, rosterDraftPath, configPatch, brief, note} を返します。brief はアシスタントがユーザーへ伝える文章です(支出の好みとタスクの種類を尋ねます)。configPatch は新たに検出したプロバイダーを delendai.config.json#providers に追加する RFC 6902 JSON Patch です——ユーザーの確認後にのみ、elicitation または CLI プロンプトで適用してください。ウィザードが確定済み設定を自ら書き込むことはありません。サブプロセスを起動しキャッシュのドラフトを書き込みますが、モデルに費用は発生しません。',
		zh: '运行提供方引导向导。在 PATH 上探测提供方 CLI,对每个检测到的工具运行尽力而为的 auth/status RPC 以获知其等级,将草稿名单写入缓存(roster.draft.json),并返回 {detected, missing, rosterDraftPath, configPatch, brief, note}。brief 是助手转达给用户的文字(询问花费偏好与任务类型)。configPatch 是一个 RFC 6902 JSON Patch,把新发现的提供方添加到 delendai.config.json#providers——仅在用户确认后,通过 elicitation 或 CLI 提示应用它。向导绝不自行写入已确认的配置。会启动子进程并写入缓存草稿;绝不为模型花钱。',
		hi: 'प्रदाता बूटस्ट्रैप विज़ार्ड चलाता है। PATH पर प्रदाता CLI की जाँच करता है, प्रत्येक पाई गई टूल के लिए उसका टियर जानने हेतु यथासंभव auth/status RPC चलाता है, कैश में एक ड्राफ्ट सूची (roster.draft.json) लिखता है, और {detected, missing, rosterDraftPath, configPatch, brief, note} लौटाता है। brief वह गद्य है जिसे सहायक उपयोगकर्ता को बताता है (खर्च वरीयता और कार्य प्रकार पूछते हुए)। configPatch एक RFC 6902 JSON Patch है जो नए खोजे गए प्रदाताओं को delendai.config.json#providers में जोड़ता है — इसे उपयोगकर्ता की पुष्टि के बाद ही elicitation / CLI प्रॉम्प्ट के माध्यम से लागू करें। विज़ार्ड कभी भी पुष्ट कॉन्फ़िग स्वयं नहीं लिखता। उपप्रक्रियाएँ शुरू करता है और कैश ड्राफ्ट लिखता है; मॉडल पर कभी खर्च नहीं करता।',
		ar: 'يشغّل معالج تهيئة المزوّدين. يفحص مسار PATH بحثًا عن أدوات سطر أوامر المزوّدين، ويشغّل استدعاء auth/status بأفضل جهد لكل أداة مكتشَفة لمعرفة فئتها، ويكتب مسودة قائمة في الذاكرة المؤقتة (roster.draft.json)، ويعيد {detected, missing, rosterDraftPath, configPatch, brief, note}. حقل brief نص ينقله المساعد إلى المستخدم (يسأل عن تفضيل الإنفاق وأنواع المهام). وحقل configPatch هو تصحيح JSON وفق RFC 6902 يضيف المزوّدين المكتشَفين حديثًا إلى delendai.config.json#providers — طبّقه عبر elicitation أو موجّه CLI فقط بعد تأكيد المستخدم. لا يكتب المعالج الإعداد المؤكَّد بنفسه أبدًا. يشغّل عمليات فرعية ويكتب مسودة الذاكرة المؤقتة؛ ولا ينفق على نموذج أبدًا.',
		th: 'รันตัวช่วยบูตสแตรปผู้ให้บริการ ตรวจ PATH เพื่อหา CLI ของผู้ให้บริการ รัน RPC auth/status แบบเท่าที่ทำได้ต่อเครื่องมือที่ตรวจพบเพื่อทราบระดับ เขียนร่างรายชื่อลงแคช (roster.draft.json) และคืนค่า {detected, missing, rosterDraftPath, configPatch, brief, note} โดย brief คือข้อความที่ผู้ช่วยส่งต่อให้ผู้ใช้ (ถามความชอบด้านค่าใช้จ่ายและประเภทงาน) configPatch คือ RFC 6902 JSON Patch ที่เพิ่มผู้ให้บริการที่เพิ่งค้นพบลงใน delendai.config.json#providers — ใช้ผ่าน elicitation / พรอมป์ CLI เฉพาะหลังจากผู้ใช้ยืนยันแล้วเท่านั้น ตัวช่วยจะไม่เขียนคอนฟิกที่ยืนยันแล้วเอง สร้างกระบวนการย่อยและเขียนร่างในแคช; ไม่เคยใช้จ่ายกับโมเดล',
		vi: 'Chạy trình hướng dẫn khởi tạo nhà cung cấp. Thăm dò PATH để tìm CLI của nhà cung cấp, chạy RPC auth/status theo khả năng cho mỗi công cụ phát hiện được để biết bậc của nó, ghi một bản nháp danh sách vào bộ nhớ đệm (roster.draft.json), và trả về {detected, missing, rosterDraftPath, configPatch, brief, note}. brief là văn bản trợ lý chuyển cho người dùng (hỏi ưu tiên chi tiêu và loại tác vụ). configPatch là một RFC 6902 JSON Patch thêm các nhà cung cấp mới phát hiện vào delendai.config.json#providers — chỉ áp dụng qua elicitation / lời nhắc CLI sau khi người dùng xác nhận. Trình hướng dẫn không bao giờ tự ghi cấu hình đã xác nhận. Tạo tiến trình con và ghi bản nháp bộ nhớ đệm; không bao giờ tiêu tiền cho mô hình.',
	},
};
