// i18n catalogue for `delendai_orchestrator-runner_format_handoff`.
//
// Per-tool i18n entry (apps/web/src/i18n/tools/orchestrator-runner/). The
// 12-lang invariant is enforced by `check-i18n.ts` once the entry opts in
// via `apps/web/src/i18n/tools/index.ts` (S9 wiring).

import type { IToolI18n } from '#I18N/tools/_shape';

export const orchestratorRunnerFormatHandoffI18n: IToolI18n = {
	description: {
		en: 'Format a routing decision (from advise_routing or invoke) into a copy-pasteable command: a cli invocation, a curl template, an MCP tools/call sketch, or a passthrough note. The safe path when executeApi:false — it formats, never spawns or spends. An api handoff references the key as $ENV_VAR and never embeds the secret, so the output is safe to log and paste.',
		es: 'Formatea una decisión de enrutamiento (de advise_routing o invoke) en un comando listo para copiar y pegar: una invocación cli, una plantilla curl, un esbozo de tools/call de MCP o una nota de passthrough. La ruta segura cuando executeApi:false: formatea, nunca lanza ni gasta. Un traspaso api referencia la clave como $ENV_VAR y nunca incrusta el secreto, así que la salida es segura para registrar y pegar.',
		fr: "Formate une décision de routage (issue d'advise_routing ou invoke) en une commande prête à copier-coller : une invocation cli, un modèle curl, une ébauche de tools/call MCP ou une note de passthrough. Le chemin sûr quand executeApi:false — il formate, ne lance ni ne dépense jamais. Un transfert api référence la clé sous la forme $ENV_VAR et n'incorpore jamais le secret, donc la sortie est sûre à journaliser et à coller.",
		de: 'Formatiert eine Routing-Entscheidung (aus advise_routing oder invoke) in einen kopierfertigen Befehl: einen cli-Aufruf, eine curl-Vorlage, eine MCP-tools/call-Skizze oder eine Passthrough-Notiz. Der sichere Weg bei executeApi:false — er formatiert, startet nie etwas und gibt kein Geld aus. Eine api-Übergabe referenziert den Schlüssel als $ENV_VAR und bettet niemals das Geheimnis ein, daher ist die Ausgabe sicher zum Loggen und Einfügen.',
		it: "Formatta una decisione di instradamento (da advise_routing o invoke) in un comando pronto da copiare e incollare: un'invocazione cli, un template curl, una bozza di tools/call MCP o una nota di passthrough. Il percorso sicuro quando executeApi:false — formatta, non avvia mai né spende. Un handoff api referenzia la chiave come $ENV_VAR e non incorpora mai il segreto, quindi l'output è sicuro da registrare e incollare.",
		pt: 'Formata uma decisão de encaminhamento (de advise_routing ou invoke) num comando pronto a copiar e colar: uma invocação cli, um modelo curl, um esboço de tools/call MCP ou uma nota de passthrough. O caminho seguro quando executeApi:false — formata, nunca lança nem gasta. Um handoff api referencia a chave como $ENV_VAR e nunca incorpora o segredo, portanto a saída é segura para registar e colar.',
		ja: 'ルーティング決定(advise_routing または invoke から)をコピー&ペースト可能なコマンドに整形します。cli の呼び出し、curl テンプレート、MCP の tools/call の下書き、または passthrough の注記です。executeApi:false のときの安全な経路——整形するだけで、起動も費用の発生もありません。api ハンドオフはキーを $ENV_VAR として参照し、シークレットを埋め込まないため、出力はログ記録や貼り付けに安全です。',
		zh: '将路由决策(来自 advise_routing 或 invoke)格式化为可复制粘贴的命令:cli 调用、curl 模板、MCP tools/call 草图或 passthrough 说明。当 executeApi:false 时的安全路径——只做格式化,绝不启动或花费。api 交接将密钥引用为 $ENV_VAR,绝不嵌入密文,因此输出可安全记录和粘贴。',
		hi: 'किसी रूटिंग निर्णय (advise_routing या invoke से) को कॉपी-पेस्ट योग्य कमांड में स्वरूपित करता है: एक cli इनवोकेशन, एक curl टेम्पलेट, एक MCP tools/call रूपरेखा, या एक passthrough नोट। executeApi:false होने पर सुरक्षित मार्ग — यह स्वरूपित करता है, कभी शुरू या खर्च नहीं करता। एक api हैंडऑफ़ कुंजी को $ENV_VAR के रूप में संदर्भित करता है और कभी गुप्त मान अंतर्निहित नहीं करता, इसलिए आउटपुट लॉग करने और पेस्ट करने के लिए सुरक्षित है।',
		ar: 'ينسّق قرار توجيه (من advise_routing أو invoke) في أمر جاهز للنسخ واللصق: استدعاء cli، أو قالب curl، أو مسودّة tools/call الخاصة بـ MCP، أو ملاحظة passthrough. المسار الآمن عندما يكون executeApi:false — فهو ينسّق فقط، ولا يشغّل ولا ينفق أبدًا. تسليم api يشير إلى المفتاح بصيغة $ENV_VAR ولا يضمّن السر أبدًا، لذا فإن المخرجات آمنة للتسجيل واللصق.',
		th: 'จัดรูปแบบการตัดสินใจกำหนดเส้นทาง (จาก advise_routing หรือ invoke) ให้เป็นคำสั่งที่คัดลอกวางได้: การเรียก cli, เทมเพลต curl, โครงร่าง tools/call ของ MCP หรือหมายเหตุ passthrough เส้นทางที่ปลอดภัยเมื่อ executeApi:false — จัดรูปแบบเท่านั้น ไม่เคยสร้างกระบวนการหรือใช้จ่าย การส่งต่อ api อ้างอิงคีย์เป็น $ENV_VAR และไม่ฝังความลับ ดังนั้นเอาต์พุตจึงปลอดภัยสำหรับการบันทึกและวาง',
		vi: 'Định dạng một quyết định định tuyến (từ advise_routing hoặc invoke) thành một lệnh có thể sao chép-dán: một lệnh gọi cli, một mẫu curl, một phác thảo tools/call MCP, hoặc một ghi chú passthrough. Đường an toàn khi executeApi:false — nó chỉ định dạng, không bao giờ tạo tiến trình hay tiêu tiền. Một bàn giao api tham chiếu khóa dưới dạng $ENV_VAR và không bao giờ nhúng bí mật, nên đầu ra an toàn để ghi log và dán.',
	},
};
