// i18n catalogue for `delendai_orchestrator-runner_advise_routing`.
//
// Per-tool i18n entry (apps/web/src/i18n/tools/orchestrator-runner/). The
// 12-lang invariant is enforced by `check-i18n.ts` once the entry opts in
// via `apps/web/src/i18n/tools/index.ts` (S9 wiring).

import type { IToolI18n } from '#I18N/tools/_shape';

export const orchestratorRunnerAdviseRoutingI18n: IToolI18n = {
	description: {
		en: "Advise which model provider to route a task to. Scores the configured roster against the task's capability hints, mode and cost preference, penalising providers the healthcheck marks unavailable, and returns the winning decision (strategy passthrough/api/cli/mcp-tool/handoff), the top-2 backups and a transparent scoring trace. Headless — it never spawns a subprocess or spends money. Pass a sessionId for sticky routing across a multi-step task.",
		es: 'Aconseja a qué proveedor de modelo enrutar una tarea. Puntúa la lista configurada según las pistas de capacidad, el modo y la preferencia de coste de la tarea, penalizando a los proveedores que el healthcheck marca como no disponibles, y devuelve la decisión ganadora (estrategia passthrough/api/cli/mcp-tool/handoff), las 2 mejores alternativas y una traza de puntuación transparente. Sin efectos: nunca lanza un subproceso ni gasta dinero. Pasa un sessionId para un enrutamiento fijo durante una tarea de varios pasos.',
		fr: "Conseille vers quel fournisseur de modèle router une tâche. Note la liste configurée selon les indices de capacité, le mode et la préférence de coût de la tâche, en pénalisant les fournisseurs que le healthcheck marque indisponibles, et renvoie la décision gagnante (stratégie passthrough/api/cli/mcp-tool/handoff), les 2 meilleures alternatives et une trace de notation transparente. Sans effet — il ne lance jamais de sous-processus et ne dépense pas d'argent. Passez un sessionId pour un routage persistant sur une tâche multi-étapes.",
		de: 'Empfiehlt, an welchen Modellanbieter eine Aufgabe geleitet werden soll. Bewertet die konfigurierte Liste anhand der Fähigkeitshinweise, des Modus und der Kostenpräferenz der Aufgabe, benachteiligt vom Healthcheck als nicht verfügbar markierte Anbieter und liefert die Gewinnerentscheidung (Strategie passthrough/api/cli/mcp-tool/handoff), die 2 besten Alternativen und eine transparente Bewertungsspur. Ohne Nebenwirkung — startet nie einen Subprozess und gibt kein Geld aus. Übergib eine sessionId für ein persistentes Routing über eine mehrstufige Aufgabe.',
		it: "Consiglia a quale provider di modello instradare un'attività. Valuta l'elenco configurato in base ai suggerimenti di capacità, alla modalità e alla preferenza di costo dell'attività, penalizzando i provider che l'healthcheck segna come non disponibili, e restituisce la decisione vincente (strategia passthrough/api/cli/mcp-tool/handoff), le 2 migliori alternative e una traccia di punteggio trasparente. Senza effetti — non avvia mai un sottoprocesso né spende denaro. Passa un sessionId per un instradamento fisso su un'attività a più passaggi.",
		pt: 'Aconselha para qual fornecedor de modelo encaminhar uma tarefa. Pontua a lista configurada segundo as pistas de capacidade, o modo e a preferência de custo da tarefa, penalizando os fornecedores que o healthcheck marca como indisponíveis, e devolve a decisão vencedora (estratégia passthrough/api/cli/mcp-tool/handoff), as 2 melhores alternativas e um rasto de pontuação transparente. Sem efeitos — nunca lança um subprocesso nem gasta dinheiro. Passa um sessionId para um encaminhamento fixo ao longo de uma tarefa de vários passos.',
		ja: 'タスクをどのモデルプロバイダーにルーティングすべきかを助言します。タスクの能力ヒント・モード・コスト設定に対して設定済みロスターを採点し、ヘルスチェックで利用不可とされたプロバイダーを減点して、勝者の決定(戦略 passthrough/api/cli/mcp-tool/handoff)、上位2つの代替案、透明なスコアリングトレースを返します。副作用なし——サブプロセスを起動せず、費用も発生しません。多段タスクで固定ルーティングするには sessionId を渡します。',
		zh: '建议将任务路由到哪个模型提供方。根据任务的能力提示、模式和成本偏好为已配置的名单打分,对健康检查标记为不可用的提供方进行惩罚,并返回获胜决策(策略 passthrough/api/cli/mcp-tool/handoff)、前 2 个备选方案以及透明的评分轨迹。无副作用——从不启动子进程,也不花钱。传入 sessionId 可在多步骤任务中保持固定路由。',
		hi: 'सलाह देता है कि किसी कार्य को किस मॉडल प्रदाता को रूट करना है। कार्य के क्षमता संकेतों, मोड और लागत वरीयता के विरुद्ध कॉन्फ़िगर की गई सूची को अंक देता है, हेल्थचेक द्वारा अनुपलब्ध चिह्नित प्रदाताओं को दंडित करता है, और विजेता निर्णय (रणनीति passthrough/api/cli/mcp-tool/handoff), शीर्ष-2 विकल्प और एक पारदर्शी स्कोरिंग ट्रेस लौटाता है। बिना प्रभाव के — यह कभी उपप्रक्रिया शुरू नहीं करता और न ही पैसा खर्च करता है। बहु-चरणीय कार्य में स्थिर रूटिंग के लिए sessionId पास करें।',
		ar: 'يقترح مزوّد النموذج الذي يجب توجيه المهمة إليه. يقيّم القائمة المُهيّأة وفق تلميحات قدرة المهمة ووضعها وتفضيل التكلفة، مُعاقِبًا المزوّدين الذين يضع فحص الصحة عليهم علامة غير متاح، ويعيد القرار الفائز (استراتيجية passthrough/api/cli/mcp-tool/handoff) وأفضل بديلين وأثر تسجيل شفاف. بلا أثر جانبي — لا يشغّل عملية فرعية ولا ينفق مالًا أبدًا. مرّر sessionId لتوجيه ثابت عبر مهمة متعددة الخطوات.',
		th: 'แนะนำว่าควรกำหนดเส้นทางงานไปยังผู้ให้บริการโมเดลรายใด ให้คะแนนรายชื่อที่กำหนดค่าไว้ตามคำใบ้ความสามารถ โหมด และความชอบด้านต้นทุนของงาน โดยหักคะแนนผู้ให้บริการที่การตรวจสอบสถานะทำเครื่องหมายว่าไม่พร้อมใช้งาน แล้วคืนค่าการตัดสินใจที่ชนะ (กลยุทธ์ passthrough/api/cli/mcp-tool/handoff) ตัวเลือกสำรอง 2 อันดับแรก และร่องรอยการให้คะแนนที่โปร่งใส ไม่มีผลข้างเคียง — ไม่เคยสร้างกระบวนการย่อยหรือใช้จ่ายเงิน ส่ง sessionId เพื่อการกำหนดเส้นทางแบบคงที่ตลอดงานหลายขั้นตอน',
		vi: 'Tư vấn nên định tuyến một tác vụ tới nhà cung cấp mô hình nào. Chấm điểm danh sách đã cấu hình theo gợi ý năng lực, chế độ và ưu tiên chi phí của tác vụ, phạt các nhà cung cấp bị healthcheck đánh dấu không khả dụng, rồi trả về quyết định thắng (chiến lược passthrough/api/cli/mcp-tool/handoff), 2 phương án dự phòng hàng đầu và một dấu vết chấm điểm minh bạch. Không tác dụng phụ — không bao giờ tạo tiến trình con hay tiêu tiền. Truyền sessionId để định tuyến cố định qua một tác vụ nhiều bước.',
	},
};
