// i18n catalogue for `delendai_orchestrator-runner_set_provider_state`.
//
// Per-tool i18n entry (apps/web/src/i18n/tools/orchestrator-runner/). The
// 12-lang invariant is enforced by `check-i18n.ts` once the entry opts in
// via `apps/web/src/i18n/tools/index.ts` (S9 wiring).

import type { IToolI18n } from '#I18N/tools/_shape';

export const orchestratorRunnerSetProviderStateI18n: IToolI18n = {
	description: {
		en: 'Manually override a provider’s availability state (available | quota-exceeded | rate-limited | unauthenticated | not-installed | model-unavailable | error), optionally bounded by an ISO `until` timestamp and a human `reason`. Updates the in-memory mirror so the next routing decision honours it immediately, and durably persists the mirror (mutex + redact + atomic write) for next-boot recovery.',
		es: 'Anula manualmente el estado de disponibilidad de un proveedor (available | quota-exceeded | rate-limited | unauthenticated | not-installed | model-unavailable | error), opcionalmente acotado por una marca de tiempo ISO `until` y una `reason` humana. Actualiza el espejo en memoria para que la siguiente decisión de enrutamiento lo respete de inmediato, y persiste el espejo de forma duradera (mutex + redacción + escritura atómica) para la recuperación en el próximo arranque.',
		fr: "Remplace manuellement l'état de disponibilité d'un fournisseur (available | quota-exceeded | rate-limited | unauthenticated | not-installed | model-unavailable | error), éventuellement borné par un horodatage ISO `until` et une `reason` humaine. Met à jour le miroir en mémoire pour que la prochaine décision de routage le respecte immédiatement, et persiste durablement le miroir (mutex + expurgation + écriture atomique) pour la récupération au prochain démarrage.",
		de: 'Überschreibt manuell den Verfügbarkeitszustand eines Anbieters (available | quota-exceeded | rate-limited | unauthenticated | not-installed | model-unavailable | error), optional begrenzt durch einen ISO-`until`-Zeitstempel und einen menschlichen `reason`. Aktualisiert den In-Memory-Spiegel, damit die nächste Routing-Entscheidung ihn sofort berücksichtigt, und persistiert den Spiegel dauerhaft (Mutex + Redaktion + atomarer Write) für die Wiederherstellung beim nächsten Start.',
		it: 'Sovrascrive manualmente lo stato di disponibilità di un provider (available | quota-exceeded | rate-limited | unauthenticated | not-installed | model-unavailable | error), opzionalmente delimitato da un timestamp ISO `until` e da una `reason` umana. Aggiorna il mirror in memoria affinché la prossima decisione di instradamento lo rispetti immediatamente, e persiste in modo durevole il mirror (mutex + redazione + scrittura atomica) per il ripristino al prossimo avvio.',
		pt: 'Substitui manualmente o estado de disponibilidade de um fornecedor (available | quota-exceeded | rate-limited | unauthenticated | not-installed | model-unavailable | error), opcionalmente delimitado por um carimbo de data/hora ISO `until` e uma `reason` humana. Atualiza o espelho em memória para que a próxima decisão de encaminhamento o respeite de imediato, e persiste o espelho de forma durável (mutex + redação + escrita atómica) para a recuperação no próximo arranque.',
		ja: 'プロバイダーの可用性状態(available | quota-exceeded | rate-limited | unauthenticated | not-installed | model-unavailable | error)を手動で上書きします。ISO 形式の `until` タイムスタンプと人間向けの `reason` で任意に範囲を限定できます。メモリ内のミラーを更新して次のルーティング決定が直ちにこれを尊重するようにし、次回起動時の復旧のためミラーを永続化します(ミューテックス + 秘匿化 + アトミック書き込み)。',
		zh: '手动覆盖某提供方的可用性状态(available | quota-exceeded | rate-limited | unauthenticated | not-installed | model-unavailable | error),可选地用 ISO 格式的 `until` 时间戳和人类可读的 `reason` 加以限定。更新内存镜像,使下一次路由决策立即遵循它,并将镜像持久化(互斥锁 + 脱敏 + 原子写入)以便下次启动时恢复。',
		hi: 'किसी प्रदाता की उपलब्धता स्थिति (available | quota-exceeded | rate-limited | unauthenticated | not-installed | model-unavailable | error) को मैन्युअल रूप से ओवरराइड करता है, वैकल्पिक रूप से एक ISO `until` टाइमस्टैम्प और मानव-पठनीय `reason` से सीमित। इन-मेमोरी मिरर को अपडेट करता है ताकि अगला रूटिंग निर्णय इसे तुरंत माने, और अगले बूट पर पुनर्प्राप्ति के लिए मिरर को स्थायी रूप से बनाए रखता है (mutex + redaction + atomic write)।',
		ar: 'يتجاوز يدويًا حالة توفّر مزوّد (available | quota-exceeded | rate-limited | unauthenticated | not-installed | model-unavailable | error)، مع إمكانية تحديدها بطابع زمني ISO عبر `until` و`reason` مقروء للبشر. يحدّث المرآة في الذاكرة كي يحترمها قرار التوجيه التالي فورًا، ويحفظ المرآة بشكل دائم (قفل متبادل + تنقيح + كتابة ذرّية) للتعافي عند الإقلاع التالي.',
		th: 'แทนที่สถานะความพร้อมใช้งานของผู้ให้บริการด้วยตนเอง (available | quota-exceeded | rate-limited | unauthenticated | not-installed | model-unavailable | error) โดยอาจจำกัดด้วยการประทับเวลา ISO `until` และ `reason` ที่มนุษย์อ่านได้ อัปเดตมิเรอร์ในหน่วยความจำเพื่อให้การตัดสินใจกำหนดเส้นทางครั้งถัดไปเคารพทันที และคงมิเรอร์ไว้อย่างถาวร (mutex + การกลบข้อมูลลับ + การเขียนแบบอะตอมมิก) เพื่อการกู้คืนเมื่อบูตครั้งถัดไป',
		vi: 'Ghi đè thủ công trạng thái khả dụng của một nhà cung cấp (available | quota-exceeded | rate-limited | unauthenticated | not-installed | model-unavailable | error), tùy chọn giới hạn bằng một dấu thời gian ISO `until` và một `reason` cho người đọc. Cập nhật bản sao trong bộ nhớ để quyết định định tuyến tiếp theo tuân theo ngay lập tức, và lưu bền vững bản sao (mutex + che bí mật + ghi nguyên tử) để khôi phục ở lần khởi động sau.',
	},
};
