// i18n catalogue for `delendai_orchestrator-runner_healthcheck_providers`.
//
// Per-tool i18n entry. The 12-lang invariant is enforced by `check-i18n.ts`
// once the entry opts in via `apps/web/src/i18n/tools/index.ts` (S9 wiring).

import type { IToolI18n } from '#I18N/tools/_shape';

export const orchestratorRunnerHealthcheckProvidersI18n: IToolI18n = {
	description: {
		en: 'Probe every configured model provider to see which are usable right now. For each it runs `command -v <cli>` (and a best-effort `--version`) on the host PATH and reports {cli.installed, path, version, auth, model, overall, installHint?}. A missing CLI carries an install hint; any hint that pipes a remote script into a shell is flagged dangerous. Refreshes the in-memory availability mirror the router uses and writes a durable snapshot. Spawns subprocesses; never spends on a model.',
		es: 'Sondea cada proveedor de modelo configurado para ver cuáles son utilizables ahora mismo. Para cada uno ejecuta `command -v <cli>` (y un `--version` de mejor esfuerzo) en el PATH del host e informa {cli.installed, path, version, auth, model, overall, installHint?}. Una CLI ausente incluye una sugerencia de instalación; cualquier sugerencia que canalice un script remoto a un shell se marca como peligrosa. Actualiza el espejo de disponibilidad en memoria que usa el enrutador y escribe una instantánea duradera. Lanza subprocesos; nunca gasta en un modelo.',
		fr: "Sonde chaque fournisseur de modèle configuré pour voir lesquels sont utilisables maintenant. Pour chacun, il exécute `command -v <cli>` (et un `--version` au mieux) sur le PATH de l'hôte et rapporte {cli.installed, path, version, auth, model, overall, installHint?}. Une CLI absente porte un conseil d'installation ; tout conseil qui redirige un script distant vers un shell est signalé comme dangereux. Rafraîchit le miroir de disponibilité en mémoire utilisé par le routeur et écrit un instantané durable. Lance des sous-processus ; ne dépense jamais pour un modèle.",
		de: 'Prüft jeden konfigurierten Modellanbieter, um zu sehen, welche gerade nutzbar sind. Für jeden führt es `command -v <cli>` (und ein `--version` nach bestem Bemühen) im PATH des Hosts aus und meldet {cli.installed, path, version, auth, model, overall, installHint?}. Eine fehlende CLI erhält einen Installationshinweis; jeder Hinweis, der ein Remote-Skript in eine Shell leitet, wird als gefährlich markiert. Aktualisiert den In-Memory-Verfügbarkeitsspiegel des Routers und schreibt einen dauerhaften Snapshot. Startet Subprozesse; gibt nie Geld für ein Modell aus.',
		it: "Sonda ogni provider di modello configurato per vedere quali sono utilizzabili ora. Per ciascuno esegue `command -v <cli>` (e un `--version` best-effort) sul PATH dell'host e riporta {cli.installed, path, version, auth, model, overall, installHint?}. Una CLI assente porta un suggerimento d'installazione; qualsiasi suggerimento che invii uno script remoto a una shell è segnalato come pericoloso. Aggiorna il mirror di disponibilità in memoria usato dal router e scrive uno snapshot durevole. Avvia sottoprocessi; non spende mai per un modello.",
		pt: 'Sonda cada fornecedor de modelo configurado para ver quais são utilizáveis agora. Para cada um executa `command -v <cli>` (e um `--version` de melhor esforço) no PATH do host e reporta {cli.installed, path, version, auth, model, overall, installHint?}. Uma CLI ausente traz uma sugestão de instalação; qualquer sugestão que canalize um script remoto para uma shell é marcada como perigosa. Atualiza o espelho de disponibilidade em memória que o encaminhador usa e escreve um instantâneo durável. Lança subprocessos; nunca gasta num modelo.',
		ja: '設定済みの各モデルプロバイダーを調べ、今すぐ使えるものを確認します。それぞれについてホストの PATH 上で `command -v <cli>`(および可能な範囲で `--version`)を実行し、{cli.installed, path, version, auth, model, overall, installHint?} を報告します。CLI が見つからない場合はインストール案内を付け、リモートスクリプトをシェルへパイプする案内は危険として印を付けます。ルーターが使うメモリ上の可用性ミラーを更新し、永続的なスナップショットを書き込みます。サブプロセスを起動しますが、モデルに費用は発生しません。',
		zh: '探测每个已配置的模型提供方,查看哪些当前可用。对每个提供方在主机 PATH 上运行 `command -v <cli>`(以及尽力而为的 `--version`),并报告 {cli.installed, path, version, auth, model, overall, installHint?}。缺失的 CLI 会附带安装提示;任何将远程脚本管道传入 shell 的提示都会被标记为危险。刷新路由器使用的内存可用性镜像并写入持久快照。会启动子进程;绝不为模型花钱。',
		hi: 'हर कॉन्फ़िगर किए गए मॉडल प्रदाता की जाँच करता है कि अभी कौन-से उपयोग योग्य हैं। प्रत्येक के लिए यह होस्ट के PATH पर `command -v <cli>` (और यथासंभव `--version`) चलाता है और {cli.installed, path, version, auth, model, overall, installHint?} रिपोर्ट करता है। अनुपस्थित CLI के साथ एक इंस्टॉल संकेत आता है; कोई भी संकेत जो किसी दूरस्थ स्क्रिप्ट को शेल में पाइप करता है उसे खतरनाक चिह्नित किया जाता है। राउटर द्वारा उपयोग किए जाने वाले इन-मेमोरी उपलब्धता मिरर को ताज़ा करता है और एक टिकाऊ स्नैपशॉट लिखता है। उपप्रक्रियाएँ शुरू करता है; मॉडल पर कभी खर्च नहीं करता।',
		ar: 'يفحص كل مزوّد نموذج مُهيّأ لمعرفة أيها قابل للاستخدام الآن. لكل واحد يشغّل `command -v <cli>` (و`--version` بأفضل جهد) على مسار PATH للمضيف ويبلّغ {cli.installed, path, version, auth, model, overall, installHint?}. الأداة الغائبة تحمل تلميح تثبيت؛ وأي تلميح يمرّر نصًا بعيدًا إلى صدفة يُوسم بأنه خطير. يحدّث مرآة التوفّر في الذاكرة التي يستخدمها الموجّه ويكتب لقطة دائمة. يشغّل عمليات فرعية؛ ولا ينفق على نموذج أبدًا.',
		th: 'ตรวจสอบผู้ให้บริการโมเดลที่กำหนดค่าไว้ทุกรายเพื่อดูว่ารายใดใช้งานได้ในตอนนี้ สำหรับแต่ละรายจะรัน `command -v <cli>` (และ `--version` เท่าที่ทำได้) บน PATH ของโฮสต์ และรายงาน {cli.installed, path, version, auth, model, overall, installHint?} CLI ที่ขาดหายจะมีคำแนะนำการติดตั้ง; คำแนะนำใดที่ไพป์สคริปต์ระยะไกลเข้าสู่เชลล์จะถูกทำเครื่องหมายว่าอันตราย รีเฟรชมิเรอร์ความพร้อมใช้งานในหน่วยความจำที่เราเตอร์ใช้ และเขียนสแนปช็อตถาวร สร้างกระบวนการย่อย; ไม่เคยใช้จ่ายกับโมเดล',
		vi: 'Thăm dò mọi nhà cung cấp mô hình đã cấu hình để xem cái nào dùng được ngay bây giờ. Với mỗi cái, nó chạy `command -v <cli>` (và `--version` nếu có thể) trên PATH của máy chủ và báo cáo {cli.installed, path, version, auth, model, overall, installHint?}. CLI thiếu sẽ kèm gợi ý cài đặt; bất kỳ gợi ý nào chuyển một script từ xa vào shell đều bị gắn cờ nguy hiểm. Làm mới bản sao khả dụng trong bộ nhớ mà bộ định tuyến dùng và ghi một ảnh chụp bền vững. Tạo tiến trình con; không bao giờ tiêu tiền cho mô hình.',
	},
};
