// i18n catalogue for `mcp-vertex_orchestrator-runner_discover_providers`.
//
// Per-tool i18n entry. The 12-lang invariant is enforced by `check-i18n.ts`
// once the entry opts in via `apps/web/src/i18n/tools/index.ts` (S9 wiring).

import type { IToolI18n } from '#I18N/tools/_shape';

export const orchestratorRunnerDiscoverProvidersI18n: IToolI18n = {
	description: {
		en: 'Discover which model-provider CLIs are installed. Runs `command -v` for claude, codex, copilot, aider, cn and agent in parallel on the host PATH and returns {detected:[{id, cliPath, version, authTier}], missing:[{id, installHint:{tool, args, pipeTo?, dangerous}}]}. A missing CLI carries a structured install hint; any hint that pipes a remote script into a shell is flagged dangerous. Spawns subprocesses; never spends on a model and never writes.',
		es: 'Descubre qué CLI de proveedores de modelos están instaladas. Ejecuta `command -v` para claude, codex, copilot, aider, cn y agent en paralelo en el PATH del host y devuelve {detected:[{id, cliPath, version, authTier}], missing:[{id, installHint:{tool, args, pipeTo?, dangerous}}]}. Una CLI ausente incluye una sugerencia de instalación estructurada; cualquier sugerencia que canalice un script remoto a un shell se marca como peligrosa. Lanza subprocesos; nunca gasta en un modelo ni escribe.',
		fr: "Détecte quelles CLI de fournisseurs de modèles sont installées. Exécute `command -v` pour claude, codex, copilot, aider, cn et agent en parallèle sur le PATH de l'hôte et renvoie {detected:[{id, cliPath, version, authTier}], missing:[{id, installHint:{tool, args, pipeTo?, dangerous}}]}. Une CLI absente porte un conseil d'installation structuré ; tout conseil qui redirige un script distant vers un shell est signalé comme dangereux. Lance des sous-processus ; ne dépense jamais pour un modèle et n'écrit jamais.",
		de: 'Ermittelt, welche Modellanbieter-CLIs installiert sind. Führt `command -v` für claude, codex, copilot, aider, cn und agent parallel im PATH des Hosts aus und gibt {detected:[{id, cliPath, version, authTier}], missing:[{id, installHint:{tool, args, pipeTo?, dangerous}}]} zurück. Eine fehlende CLI erhält einen strukturierten Installationshinweis; jeder Hinweis, der ein Remote-Skript in eine Shell leitet, wird als gefährlich markiert. Startet Subprozesse; gibt nie Geld für ein Modell aus und schreibt nie.',
		it: "Rileva quali CLI di provider di modelli sono installate. Esegue `command -v` per claude, codex, copilot, aider, cn e agent in parallelo sul PATH dell'host e restituisce {detected:[{id, cliPath, version, authTier}], missing:[{id, installHint:{tool, args, pipeTo?, dangerous}}]}. Una CLI assente porta un suggerimento d'installazione strutturato; qualsiasi suggerimento che invii uno script remoto a una shell è segnalato come pericoloso. Avvia sottoprocessi; non spende mai per un modello e non scrive mai.",
		pt: 'Descobre quais CLIs de fornecedores de modelos estão instaladas. Executa `command -v` para claude, codex, copilot, aider, cn e agent em paralelo no PATH do host e devolve {detected:[{id, cliPath, version, authTier}], missing:[{id, installHint:{tool, args, pipeTo?, dangerous}}]}. Uma CLI ausente traz uma sugestão de instalação estruturada; qualquer sugestão que canalize um script remoto para uma shell é marcada como perigosa. Lança subprocessos; nunca gasta num modelo nem escreve.',
		ja: 'インストール済みのモデルプロバイダー CLI を検出します。ホストの PATH 上で claude、codex、copilot、aider、cn、agent に対して `command -v` を並列に実行し、{detected:[{id, cliPath, version, authTier}], missing:[{id, installHint:{tool, args, pipeTo?, dangerous}}]} を返します。見つからない CLI には構造化されたインストール案内が付き、リモートスクリプトをシェルへパイプする案内は危険として印を付けます。サブプロセスを起動しますが、モデルに費用は発生せず、書き込みも行いません。',
		zh: '发现已安装的模型提供方 CLI。在主机 PATH 上并行为 claude、codex、copilot、aider、cn 和 agent 运行 `command -v`,并返回 {detected:[{id, cliPath, version, authTier}], missing:[{id, installHint:{tool, args, pipeTo?, dangerous}}]}。缺失的 CLI 会附带结构化安装提示;任何将远程脚本管道传入 shell 的提示都会被标记为危险。会启动子进程;绝不为模型花钱,也不写入。',
		hi: 'पता लगाता है कि कौन-सी मॉडल-प्रदाता CLI इंस्टॉल हैं। होस्ट के PATH पर claude, codex, copilot, aider, cn और agent के लिए समानांतर में `command -v` चलाता है और {detected:[{id, cliPath, version, authTier}], missing:[{id, installHint:{tool, args, pipeTo?, dangerous}}]} लौटाता है। अनुपस्थित CLI के साथ एक संरचित इंस्टॉल संकेत आता है; कोई भी संकेत जो किसी दूरस्थ स्क्रिप्ट को शेल में पाइप करता है उसे खतरनाक चिह्नित किया जाता है। उपप्रक्रियाएँ शुरू करता है; मॉडल पर कभी खर्च नहीं करता और न लिखता है।',
		ar: 'يكتشف أدوات سطر الأوامر (CLI) لمزوّدي النماذج المثبَّتة. يشغّل `command -v` لـ claude وcodex وcopilot وaider وcn وagent بالتوازي على مسار PATH للمضيف ويعيد {detected:[{id, cliPath, version, authTier}], missing:[{id, installHint:{tool, args, pipeTo?, dangerous}}]}. الأداة الغائبة تحمل تلميح تثبيت منظَّمًا؛ وأي تلميح يمرّر نصًا بعيدًا إلى صدفة يُوسم بأنه خطير. يشغّل عمليات فرعية؛ ولا ينفق على نموذج أبدًا ولا يكتب.',
		th: 'ค้นหาว่า CLI ของผู้ให้บริการโมเดลใดถูกติดตั้งไว้ รัน `command -v` สำหรับ claude, codex, copilot, aider, cn และ agent แบบขนานบน PATH ของโฮสต์ และคืนค่า {detected:[{id, cliPath, version, authTier}], missing:[{id, installHint:{tool, args, pipeTo?, dangerous}}]} CLI ที่ขาดหายจะมีคำแนะนำการติดตั้งแบบมีโครงสร้าง; คำแนะนำใดที่ไพป์สคริปต์ระยะไกลเข้าสู่เชลล์จะถูกทำเครื่องหมายว่าอันตราย สร้างกระบวนการย่อย; ไม่เคยใช้จ่ายกับโมเดลและไม่เคยเขียน',
		vi: 'Phát hiện những CLI của nhà cung cấp mô hình nào đã được cài đặt. Chạy `command -v` cho claude, codex, copilot, aider, cn và agent song song trên PATH của máy chủ và trả về {detected:[{id, cliPath, version, authTier}], missing:[{id, installHint:{tool, args, pipeTo?, dangerous}}]}. CLI thiếu sẽ kèm gợi ý cài đặt có cấu trúc; bất kỳ gợi ý nào chuyển một script từ xa vào shell đều bị gắn cờ nguy hiểm. Tạo tiến trình con; không bao giờ tiêu tiền cho mô hình và không bao giờ ghi.',
	},
};
