// i18n catalogue for `mcp-vertex_orchestrator-runner_invoke`.
//
// Per-tool i18n entry (apps/web/src/i18n/tools/orchestrator-runner/). The
// 12-lang invariant is enforced by `check-i18n.ts` once the entry opts in
// via `apps/web/src/i18n/tools/index.ts` (S9 wiring).

import type { IToolI18n } from '#I18N/tools/_shape';

export const orchestratorRunnerInvokeI18n: IToolI18n = {
	description: {
		en: "Execute a task on the best-scored provider and return its structured result. Plans a fallback chain (rerank|tier-down), enforces a wall-clock timeout that fires the per-kind cancellation ladder, and — CRITICAL SAFETY — never spends the user's API money unless executeApi is on AND a one-time signed confirmation token (from an MCP elicitation) authorises THAT invocation. With executeApi:false, api/cli routes return an 'execution-disabled' error and a handoff instead of spending. Returns {decision, result{text, structuredContent?, usage?, costUsd?}, invocationId, sessionId} on success, or {decision, error{code, tried, nextAvailableAt}, userMessage} otherwise.",
		es: "Ejecuta una tarea en el proveedor mejor puntuado y devuelve su resultado estructurado. Planifica una cadena de reserva (rerank|tier-down), aplica un tiempo límite de reloj que dispara la escalera de cancelación por tipo y —SEGURIDAD CRÍTICA— nunca gasta el dinero de la API del usuario a menos que executeApi esté activo Y un token de confirmación firmado de un solo uso (de una elicitación MCP) autorice ESA invocación. Con executeApi:false, las rutas api/cli devuelven un error 'execution-disabled' y un traspaso en lugar de gastar. Devuelve {decision, result{text, structuredContent?, usage?, costUsd?}, invocationId, sessionId} si tiene éxito, o {decision, error{code, tried, nextAvailableAt}, userMessage} en caso contrario.",
		fr: "Exécute une tâche sur le fournisseur le mieux noté et renvoie son résultat structuré. Planifie une chaîne de repli (rerank|tier-down), applique un délai d'horloge qui déclenche l'échelle d'annulation par type et — SÉCURITÉ CRITIQUE — ne dépense jamais l'argent d'API de l'utilisateur sauf si executeApi est activé ET qu'un jeton de confirmation signé à usage unique (issu d'une élicitation MCP) autorise CETTE invocation. Avec executeApi:false, les routes api/cli renvoient une erreur 'execution-disabled' et un transfert au lieu de dépenser. Renvoie {decision, result{text, structuredContent?, usage?, costUsd?}, invocationId, sessionId} en cas de succès, sinon {decision, error{code, tried, nextAvailableAt}, userMessage}.",
		de: "Führt eine Aufgabe auf dem bestbewerteten Anbieter aus und gibt dessen strukturiertes Ergebnis zurück. Plant eine Fallback-Kette (rerank|tier-down), erzwingt ein Wanduhr-Timeout, das die Abbruchleiter je Art auslöst, und — KRITISCHE SICHERHEIT — gibt niemals das API-Geld des Nutzers aus, es sei denn, executeApi ist aktiv UND ein einmaliges signiertes Bestätigungs-Token (aus einer MCP-Elicitation) autorisiert GENAU diese Ausführung. Mit executeApi:false geben api/cli-Routen einen 'execution-disabled'-Fehler und eine Übergabe zurück, statt Geld auszugeben. Gibt bei Erfolg {decision, result{text, structuredContent?, usage?, costUsd?}, invocationId, sessionId} zurück, sonst {decision, error{code, tried, nextAvailableAt}, userMessage}.",
		it: "Esegue un'attività sul provider con il punteggio migliore e restituisce il suo risultato strutturato. Pianifica una catena di fallback (rerank|tier-down), applica un timeout di orologio che innesca la scala di annullamento per tipo e — SICUREZZA CRITICA — non spende mai il denaro dell'API dell'utente a meno che executeApi sia attivo E un token di conferma firmato monouso (da un'elicitazione MCP) autorizzi QUELLA invocazione. Con executeApi:false, le rotte api/cli restituiscono un errore 'execution-disabled' e un handoff invece di spendere. Restituisce {decision, result{text, structuredContent?, usage?, costUsd?}, invocationId, sessionId} in caso di successo, altrimenti {decision, error{code, tried, nextAvailableAt}, userMessage}.",
		pt: "Executa uma tarefa no fornecedor com melhor pontuação e devolve o seu resultado estruturado. Planeia uma cadeia de recurso (rerank|tier-down), aplica um tempo limite de relógio que dispara a escada de cancelamento por tipo e — SEGURANÇA CRÍTICA — nunca gasta o dinheiro da API do utilizador a menos que executeApi esteja ativo E um token de confirmação assinado de uso único (de uma elicitação MCP) autorize AQUELA invocação. Com executeApi:false, as rotas api/cli devolvem um erro 'execution-disabled' e um handoff em vez de gastar. Devolve {decision, result{text, structuredContent?, usage?, costUsd?}, invocationId, sessionId} em caso de sucesso, ou {decision, error{code, tried, nextAvailableAt}, userMessage} caso contrário.",
		ja: "最もスコアの高いプロバイダーでタスクを実行し、構造化された結果を返します。フォールバックチェーン(rerank|tier-down)を計画し、種類ごとのキャンセルラダーを起動する実時間タイムアウトを適用し、そして——重大な安全策——executeApi が有効で、かつ(MCP エリシテーションからの)使い捨ての署名済み確認トークンがその実行を承認しない限り、ユーザーの API 費用を決して使いません。executeApi:false の場合、api/cli 経路は費用を使わず 'execution-disabled' エラーとハンドオフを返します。成功時は {decision, result{text, structuredContent?, usage?, costUsd?}, invocationId, sessionId}、そうでなければ {decision, error{code, tried, nextAvailableAt}, userMessage} を返します。",
		zh: "在评分最高的提供方上执行任务并返回其结构化结果。规划回退链(rerank|tier-down),施加会触发按类型取消阶梯的挂钟超时,并且——关键安全——除非 executeApi 已开启且一次性签名确认令牌(来自 MCP elicitation)授权了那次调用,否则绝不花费用户的 API 费用。当 executeApi:false 时,api/cli 路由返回 'execution-disabled' 错误和一次交接,而不是花钱。成功时返回 {decision, result{text, structuredContent?, usage?, costUsd?}, invocationId, sessionId},否则返回 {decision, error{code, tried, nextAvailableAt}, userMessage}。",
		hi: "सर्वोत्तम-अंकित प्रदाता पर कोई कार्य निष्पादित करता है और उसका संरचित परिणाम लौटाता है। एक फ़ॉलबैक शृंखला (rerank|tier-down) की योजना बनाता है, एक वॉल-क्लॉक टाइमआउट लागू करता है जो प्रति-प्रकार रद्दीकरण सीढ़ी चलाता है, और — महत्वपूर्ण सुरक्षा — तब तक कभी उपयोगकर्ता का API पैसा खर्च नहीं करता जब तक executeApi चालू न हो और (MCP elicitation से) एक बार का हस्ताक्षरित पुष्टि टोकन उस विशेष निष्पादन को अधिकृत न करे। executeApi:false के साथ, api/cli मार्ग खर्च करने के बजाय एक 'execution-disabled' त्रुटि और एक हैंडऑफ़ लौटाते हैं। सफलता पर {decision, result{text, structuredContent?, usage?, costUsd?}, invocationId, sessionId} लौटाता है, अन्यथा {decision, error{code, tried, nextAvailableAt}, userMessage}।",
		ar: "ينفّذ مهمة على المزوّد الأعلى تقييمًا ويعيد نتيجته المنظَّمة. يخطّط سلسلة احتياطية (rerank|tier-down)، ويفرض مهلة زمنية بساعة الحائط تُطلق سلّم الإلغاء حسب النوع، و— أمانٌ حرِج — لا ينفق مال واجهة برمجة التطبيقات الخاص بالمستخدم أبدًا ما لم يكن executeApi مُفعّلًا وكان رمز تأكيد موقّع لمرة واحدة (من استنباط MCP) يصرّح بذلك الاستدعاء تحديدًا. مع executeApi:false، تُعيد مسارات api/cli خطأ 'execution-disabled' وتسليمًا بدلًا من الإنفاق. يُعيد {decision, result{text, structuredContent?, usage?, costUsd?}, invocationId, sessionId} عند النجاح، وإلا {decision, error{code, tried, nextAvailableAt}, userMessage}.",
		th: "รันงานบนผู้ให้บริการที่ได้คะแนนดีที่สุดและคืนผลลัพธ์แบบมีโครงสร้าง วางแผนสายสำรอง (rerank|tier-down) บังคับใช้เวลาหมดเวลาตามนาฬิกาจริงที่จุดชนวนบันไดการยกเลิกตามชนิด และ — ความปลอดภัยสำคัญยิ่ง — จะไม่ใช้จ่ายเงิน API ของผู้ใช้เด็ดขาด เว้นแต่ executeApi เปิดอยู่และมีโทเคนยืนยันที่ลงนามแบบใช้ครั้งเดียว (จาก MCP elicitation) อนุญาตการเรียกครั้งนั้นโดยเฉพาะ เมื่อ executeApi:false เส้นทาง api/cli จะคืนข้อผิดพลาด 'execution-disabled' และการส่งต่อแทนการใช้จ่าย คืน {decision, result{text, structuredContent?, usage?, costUsd?}, invocationId, sessionId} เมื่อสำเร็จ มิฉะนั้น {decision, error{code, tried, nextAvailableAt}, userMessage}",
		vi: "Thực thi một tác vụ trên nhà cung cấp được chấm điểm cao nhất và trả về kết quả có cấu trúc của nó. Lập kế hoạch chuỗi dự phòng (rerank|tier-down), áp dụng thời gian chờ theo đồng hồ thực kích hoạt thang hủy theo từng loại, và — AN TOÀN QUAN TRỌNG — không bao giờ tiêu tiền API của người dùng trừ khi executeApi được bật VÀ một token xác nhận có chữ ký dùng một lần (từ một elicitation MCP) cho phép CHÍNH lần gọi đó. Với executeApi:false, các tuyến api/cli trả về lỗi 'execution-disabled' và một bàn giao thay vì tiêu tiền. Trả về {decision, result{text, structuredContent?, usage?, costUsd?}, invocationId, sessionId} khi thành công, nếu không thì {decision, error{code, tried, nextAvailableAt}, userMessage}.",
	},
};
