/**
 * first-party-index.ts — f00141 S1: the bundled first-party plugin
 * index. Plain data, no I/O; the resolver reads it as the default
 * source. Update this list when adding a new first-party plugin.
 */
import type { IPluginRegistrySource } from '../contracts/interfaces/plugin-registry.interface';

import { GENERATED_FIRST_PARTY_MANIFEST_ENTRIES } from './generated/first-party-manifest-entries.generated';

export const FIRST_PARTY_PLUGIN_INDEX: IPluginRegistrySource = {
	origin: 'first-party',
	entries: [
		{
			origin: 'first-party',
			id: 'api',
			package: '@mcp-vertex/api',
			summary: 'REST/GraphQL API surface for mcp-vertex plugins.',
			tags: ['api', 'surface'],
			permissions: ['process', 'network'],
		},
		{
			origin: 'first-party',
			id: 'audit',
			package: '@mcp-vertex/audit',
			summary:
				'Multi-model audit planning + consolidation; f00139 adds self_audit dogfood loop.',
			tags: ['audit', 'multi-model', 'self-improvement', 'f00077'],
			permissions: ['filesystem-read', 'filesystem-write', 'network'],
			defaultPreset: 'standard',
		},
		{
			origin: 'first-party',
			id: 'auto-agent-selector',
			package: '@mcp-vertex/auto-agent-selector',
			summary:
				'Zero-config multi-agent routing (cost↔quality dial, auto_recommend, escalation).',
			tags: ['routing', 'agents', 'f00119'],
			permissions: ['process', 'network'],
			defaultPreset: 'standard',
		},
		{
			origin: 'first-party',
			id: 'auto-plugin-selector',
			package: '@mcp-vertex/auto-plugin-selector',
			summary:
				'Recommends the best plugin set for this project from its signals (manifest, files, git, task).',
			tags: ['plugins', 'catalog', 'routing', 'f00142'],
			permissions: ['filesystem-read'],
		},
		{
			origin: 'first-party',
			id: 'browser',
			package: '@mcp-vertex/browser',
			summary: 'Headless browser automation tools.',
			tags: ['browser', 'automation'],
			permissions: ['browser', 'network'],
		},
		{
			origin: 'first-party',
			id: 'cache',
			package: '@mcp-vertex/cache',
			summary:
				'Cache-eviction rules and lifecycle for plugin scratch dirs.',
			tags: ['cache', 'lifecycle', 'f00072'],
			permissions: ['filesystem-read', 'filesystem-write'],
		},
		{
			origin: 'first-party',
			id: 'changelog',
			package: '@mcp-vertex/changelog',
			summary: 'Conventional-commits changelog + release plan generator.',
			tags: ['changelog', 'release', 'f00131'],
			permissions: ['git-read'],
		},
		{
			origin: 'first-party',
			id: 'completion',
			package: '@mcp-vertex/completion',
			summary:
				'Task-completion notifier: records an agent declaring its original task done + reviewed and pushes a notification.',
			tags: ['completion', 'notification', 'f00159'],
			permissions: ['filesystem-read', 'filesystem-write'],
		},
		{
			origin: 'first-party',
			id: 'container',
			package: '@mcp-vertex/container',
			summary:
				'Container inspection + lint (docker ps/images, k8s, Dockerfile rules).',
			tags: ['container', 'docker', 'kubernetes', 'f00133'],
			permissions: ['container', 'process'],
			defaultPreset: 'standard',
		},
		{
			origin: 'first-party',
			id: 'context-for-change',
			package: '@mcp-vertex/context-for-change',
			summary:
				'Compact change-context orchestrator that combines diff, symbols, tests, docs and conventions.',
			tags: ['context', 'orchestration', 'f00165'],
			permissions: ['filesystem-read'],
		},
		{
			origin: 'first-party',
			id: 'conventions',
			package: '@mcp-vertex/conventions',
			summary:
				'Repo file-convention enforcement (interface, constant, service, tool …).',
			tags: ['conventions', 'f00037'],
			permissions: ['filesystem-read'],
		},
		{
			origin: 'first-party',
			id: 'database',
			package: '@mcp-vertex/database',
			summary:
				'Database schema/introspection tools (read-only, offline).',
			tags: ['database', 'schema', 'f00128'],
			permissions: ['database'],
			defaultPreset: 'standard',
		},
		{
			origin: 'first-party',
			id: 'deps',
			package: '@mcp-vertex/deps',
			summary:
				'Dependency inventory + offline health (deps_list, deps_check, deps_audit, deps_licenses, deps_tree).',
			tags: ['deps', 'licenses', 'f00003', 'f00136'],
			permissions: ['filesystem-read', 'network'],
			defaultPreset: 'standard',
		},
		{
			origin: 'first-party',
			id: 'diagram',
			package: '@mcp-vertex/diagram',
			summary: 'Diagram generator (mermaid, dot) from code structure.',
			tags: ['diagram', 'docs', 'f00132'],
			permissions: ['filesystem-read', 'filesystem-write'],
			defaultPreset: 'standard',
		},
		{
			origin: 'first-party',
			id: 'docs',
			package: '@mcp-vertex/docs',
			summary: 'Doc generation, search, and rendered catalog.',
			tags: ['docs', 'catalog'],
			permissions: ['filesystem-read', 'filesystem-write'],
			defaultPreset: 'standard',
		},
		{
			origin: 'first-party',
			id: 'env',
			package: '@mcp-vertex/env',
			summary:
				'Environment config validation (.env check + schema + env_explains).',
			tags: ['env', 'config', 'f00135'],
			permissions: ['env-read'],
			defaultPreset: 'standard',
		},
		{
			origin: 'first-party',
			id: 'error-reporting',
			package: '@mcp-vertex/error-reporting',
			summary:
				'Automatic mcp-vertex error reporting: opens de-duplicated GitHub issues for internal failures (enabled by default).',
			tags: ['error-reporting', 'github', 'issues', 'f00158'],
			permissions: ['network', 'forge-write'],
			defaultPreset: 'standard',
		},
		{
			origin: 'first-party',
			id: 'external-mcps',
			package: '@mcp-vertex/external-mcps',
			summary:
				'Compose third-party MCP servers through the catalog + human ack.',
			tags: ['external-mcps', 'composition', 'f00068'],
			permissions: ['network', 'process'],
		},
		{
			origin: 'first-party',
			id: 'forge',
			package: '@mcp-vertex/forge',
			summary: 'Forge (GitHub/GitLab) wrappers — PRs, CI, issues.',
			tags: ['forge', 'git', 'ci'],
			permissions: ['forge-read', 'forge-write', 'network'],
		},
		{
			origin: 'first-party',
			id: 'git',
			package: '@mcp-vertex/git',
			summary: 'Git wrappers (PR list/view, diff, changelog, extended).',
			tags: ['git', 'changelog', 'f00136'],
			permissions: ['git-read', 'git-write'],
		},
		{
			origin: 'first-party',
			id: 'i18n',
			package: '@mcp-vertex/i18n',
			summary:
				'i18n key/interpolation validation across locale JSON files.',
			tags: ['i18n', 'l10n', 'f00134'],
			permissions: ['filesystem-read'],
			defaultPreset: 'standard',
		},
		{
			origin: 'first-party',
			id: 'issues',
			package: '@mcp-vertex/issues',
			summary: 'Issue tracker adapters.',
			tags: ['issues'],
			permissions: ['forge-read', 'forge-write', 'network'],
		},
		{
			origin: 'first-party',
			id: 'link-check',
			package: '@mcp-vertex/link-check',
			summary: 'Markdown link checker.',
			tags: ['docs', 'links'],
			permissions: ['filesystem-read'],
		},
		{
			origin: 'first-party',
			id: 'logs',
			package: '@mcp-vertex/logs',
			summary: 'Structured logs reader (tail, query, redact).',
			tags: ['logs', 'observability'],
			permissions: ['filesystem-read', 'filesystem-write'],
		},
		{
			origin: 'first-party',
			id: 'memory',
			package: '@mcp-vertex/memory',
			summary: 'Persistent memory store (BM25 + recall, save, search).',
			tags: ['memory', 'persistence'],
			permissions: ['filesystem-read', 'filesystem-write'],
		},
		{
			origin: 'first-party',
			id: 'notification',
			package: '@mcp-vertex/notification',
			summary: 'Notification + lock-await primitives.',
			tags: ['notification', 'concurrency'],
			permissions: ['filesystem-read', 'filesystem-write'],
		},
		{
			origin: 'first-party',
			id: 'observability',
			package: '@mcp-vertex/observability',
			summary: 'Observability surface (metrics, errors, telemetry).',
			tags: ['observability'],
			permissions: ['filesystem-read', 'filesystem-write'],
		},
		{
			origin: 'first-party',
			id: 'orchestrator-runner',
			package: '@mcp-vertex/orchestrator-runner',
			summary: 'Orchestrator-runner runtime utilities.',
			tags: ['orchestrator', 'runner'],
			permissions: ['process', 'network'],
		},
		{
			origin: 'first-party',
			id: 'perf',
			package: '@mcp-vertex/perf',
			summary: 'Performance bench/bundle/profile tools.',
			tags: ['perf', 'benchmark', 'f00126'],
			permissions: ['filesystem-read', 'process'],
		},
		{
			origin: 'first-party',
			id: 'prompt-eval',
			package: '@mcp-vertex/prompt-eval',
			summary: 'Prompt-eval harness (golden prompts, scoring).',
			tags: ['prompts', 'eval'],
			permissions: ['filesystem-read', 'process'],
		},
		{
			origin: 'first-party',
			id: 'prompts-pack',
			package: '@mcp-vertex/prompts-pack',
			summary:
				'Project-aware MCP prompts (explain-this-code, write-tests-for, review-this-diff, etc.).',
			tags: ['prompts', 'f00138'],
			permissions: ['filesystem-read'],
			defaultPreset: 'standard',
		},
		{
			origin: 'first-party',
			id: 'proposals',
			package: '@mcp-vertex/proposals',
			summary: 'Proposals workflow + multi-agent (swarm) orchestration.',
			tags: ['proposals', 'swarm', 'orchestration'],
			permissions: [
				'filesystem-read',
				'filesystem-write',
				'git-read',
				'git-write',
			],
		},
		{
			origin: 'first-party',
			id: 'quality',
			package: '@mcp-vertex/quality',
			summary:
				'Quality gates: coverage, complexity, lint, type-check orchestration.',
			tags: ['quality', 'gates', 'f00036', 'f00136'],
			permissions: ['filesystem-read', 'process'],
			defaultPreset: 'standard',
		},
		{
			origin: 'first-party',
			id: 'refactor',
			package: '@mcp-vertex/refactor',
			summary:
				'Refactor primitives (symbols, definition, references, rename, codemod).',
			tags: ['refactor', 'f00123'],
			permissions: ['filesystem-read', 'filesystem-write'],
			defaultPreset: 'standard',
		},
		{
			origin: 'first-party',
			id: 'rules',
			package: '@mcp-vertex/rules',
			summary: 'Lint/type rules engine (frameworks, dogmas, presets).',
			tags: ['rules', 'lint'],
			permissions: ['filesystem-read'],
			defaultPreset: 'standard',
		},
		...GENERATED_FIRST_PARTY_MANIFEST_ENTRIES,
		{
			origin: 'first-party',
			id: 'security',
			package: '@mcp-vertex/security',
			summary: 'Security audit (CVEs, SAST, secrets, env).',
			tags: ['security', 'audit', 'f00122'],
			permissions: ['filesystem-read', 'env-read'],
		},
		{
			origin: 'first-party',
			id: 'skills-pack',
			package: '@mcp-vertex/skills-pack',
			summary:
				'Curated skill pack (debugging, perf, pr-review, security, incident, migration).',
			tags: ['skills', 'f00137'],
			permissions: ['filesystem-read'],
			defaultPreset: 'standard',
		},
		{
			origin: 'first-party',
			id: 'status-marker',
			package: '@mcp-vertex/status-marker',
			summary: 'Status marker + closure canonical line.',
			tags: ['status-marker', 'closure'],
			permissions: ['filesystem-read'],
		},
		{
			origin: 'first-party',
			id: 'tech-debt',
			package: '@mcp-vertex/tech-debt',
			summary: 'Tech-debt scanner (TODO/FIXME/HACK inventory).',
			tags: ['tech-debt'],
			permissions: ['filesystem-read'],
		},
		{
			origin: 'first-party',
			id: 'test-convention',
			package: '@mcp-vertex/test-convention',
			summary:
				'Test-file convention enforcement (spec path, mock style, forbidden patterns).',
			tags: ['tests', 'convention'],
			permissions: ['filesystem-read'],
		},
		{
			origin: 'first-party',
			id: 'test-policy',
			package: '@mcp-vertex/test-policy',
			summary: 'Test policy mode (TDD, tests-after, free, none).',
			tags: ['tests', 'policy'],
			permissions: ['filesystem-read', 'filesystem-write'],
			defaultPreset: 'standard',
		},
		{
			origin: 'first-party',
			id: 'usage-tracking',
			package: '@mcp-vertex/usage-tracking',
			summary: 'Per-token/per-call usage tracking (spend, budget).',
			tags: ['usage', 'spend'],
			permissions: ['filesystem-read', 'filesystem-write'],
		},
		{
			origin: 'first-party',
			id: 'web-fetch',
			package: '@mcp-vertex/web-fetch',
			summary: 'Web fetch (allow-listed URLs only).',
			tags: ['web', 'fetch'],
			permissions: ['network'],
		},
	],
};
