export const ADAPTIVE_OPTIMIZER_DEPENDS_ON = [
	'@delendai/prompt-eval',
	'@delendai/usage-tracking',
	'@delendai/perf',
	'@delendai/auto-agent-selector',
	'@delendai/auto-plugin-selector',
] as const;

export const DEFAULT_ADAPTIVE_OPTIMIZER_MAX_BYTES = 2000;
export const ADAPTIVE_OPTIMIZER_MAX_CANDIDATES = 25;
export const ADAPTIVE_OPTIMIZER_MAX_PLUGIN_SET = 20;
export const ADAPTIVE_OPTIMIZER_DEFAULT_BUDGET_DIAL = 7;
export const ADAPTIVE_OPTIMIZER_UTILITY_SCALE = 100;

export const OPTIMIZATION_RELEVANCE_WEIGHT = 15;
export const OPTIMIZATION_CONFIDENCE_WEIGHT = 10;
export const OPTIMIZATION_TOKEN_TAX_WEIGHT = 12;
export const OPTIMIZATION_LATENCY_TAX_WEIGHT = 8;
export const OPTIMIZATION_PERMISSION_RISK_WEIGHT = 15;

export const OPTIMIZATION_TOKEN_COST_NORMALIZER = 4000;
export const OPTIMIZATION_LATENCY_MS_NORMALIZER = 3000;
export const OPTIMIZATION_PERMISSION_RISK_NORMALIZER = 10;

export const OPTIMIZATION_DEFAULT_SUCCESS_RATE = 0.55;
export const OPTIMIZATION_DEFAULT_RELEVANCE = 0.45;
export const OPTIMIZATION_DEFAULT_CONFIDENCE = 0.45;
export const OPTIMIZATION_DEFAULT_LATENCY_MS = 350;
export const OPTIMIZATION_DEFAULT_TOKEN_COST = 160;
export const OPTIMIZATION_RELEVANCE_OVERLAP_WEIGHT = 0.35;
export const OPTIMIZATION_RELEVANCE_PLUGIN_MATCH_WEIGHT = 0.08;
export const OPTIMIZATION_CONFIDENCE_AGENT_BONUS = 0.1;
export const OPTIMIZATION_CONFIDENCE_USAGE_MIRROR_BONUS = 0.02;
export const OPTIMIZATION_CONFIDENCE_EXPERIMENT_HOOK_BONUS = 0.03;
export const OPTIMIZATION_CONFIDENCE_PROVIDER_MATCH_BONUS = 0.1;
export const OPTIMIZATION_CONFIDENCE_PROVIDER_TOP_BONUS = 0.05;
export const OPTIMIZATION_SUCCESS_PROVIDER_TOP_BONUS = 0.18;
export const OPTIMIZATION_SUCCESS_PROVIDER_MATCH_BONUS = 0.08;
export const OPTIMIZATION_SUCCESS_PLUGIN_MATCH_BONUS = 0.05;
export const OPTIMIZATION_SUCCESS_PROMPT_BONUS = 0.04;
export const OPTIMIZATION_SUCCESS_DESCRIPTION_BONUS = 0.03;
export const OPTIMIZATION_LATENCY_PLUGIN_MATCH_BONUS_MS = 40;
export const OPTIMIZATION_LATENCY_PERMISSION_BONUS_MS = 25;
export const OPTIMIZATION_LATENCY_COST_TIER_BONUS_MS = 60;
